/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/spelling`
 */
// #region Variables
export declare const spelling: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, [import("@flint.fyi/core").Rule<{
  readonly description: "Runs the CSpell spell checker on any source code file.";
  readonly id: "cspell";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "issue" | "issueWithReplacement", undefined>]>;
// #endregion