/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/vitest`
 */
// #region Variables
export declare const vitest: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [StatementPaddingRule, StatementPaddingRule, StatementPaddingRule, StatementPaddingRule, StatementPaddingRule, StatementPaddingRule, StatementPaddingRule, import("@flint.fyi/core").Rule<{
  readonly description: "Reports importing from `node:test`.";
  readonly id: "nodeTestImports";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "nodeTestImport", undefined>, StatementPaddingRule, import("@flint.fyi/core").Rule<{
  readonly description: "Reports importing from `node:test`.";
  readonly id: "testCasesWithinDescribes";
  readonly presets: readonly ["stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "standalone", undefined>]>;
// #endregion