/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/jsx`
 */
// #region Variables
export declare const jsx: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all" | "javascript" | "typescript", [import("@flint.fyi/core").Rule<{
  readonly description: "Disallow the use of the `accessKey` / `accesskey` attribute on JSX elements.";
  readonly id: "accessKeys";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "avoidAccessKey", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports elements that require alt text but are missing it.";
  readonly id: "altTexts";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingAlt", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports anchor elements with ambiguous text that doesn't describe the link destination.";
  readonly id: "anchorAmbiguousText";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "ambiguousText", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports anchor elements without accessible content.";
  readonly id: "anchorContent";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingContent", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports invalid usage of anchor elements.";
  readonly id: "anchorValidity";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidHref" | "missingHref" | "shouldBeButton", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports elements with aria-activedescendant without tabIndex.";
  readonly id: "ariaActiveDescendantTabIndex";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingTabIndex", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports elements with aria-hidden='true' that are focusable.";
  readonly id: "ariaHiddenFocusables";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "ariaHiddenFocusable", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports invalid ARIA properties.";
  readonly id: "ariaProps";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidAriaProp", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports ARIA properties with invalid value types.";
  readonly id: "ariaPropTypes";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidPropType", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports invalid or abstract ARIA roles.";
  readonly id: "ariaRoleValidity";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidRole", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports ARIA attributes on elements that don't support them.";
  readonly id: "ariaUnsupportedElements";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unsupportedElement", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Ensure the autocomplete attribute is correct and suitable for the form field.";
  readonly id: "autocomplete";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalid", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports autoFocus props that are not set to false.";
  readonly id: "autoFocusProps";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noAutoFocus", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer shorthand boolean attributes over explicit {true} values in JSX.";
  readonly id: "booleanValues";
  readonly presets: readonly ["stylistic"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferShorthand", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallow unnecessary JSX curly braces around literals and JSX elements.";
  readonly id: "bracedStatements";
  readonly presets: readonly ["stylistic"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unnecessaryBraces", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports button elements without an explicit type attribute.";
  readonly id: "buttonTypes";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidType" | "missingType", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports usage of the children prop.";
  readonly id: "childrenProps";
  readonly presets: readonly ["stylistic"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noChildrenProp", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports onClick without keyboard event handlers.";
  readonly id: "clickEventKeyEvents";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingKeyEvent", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports JSX text nodes that contain comment syntax but are rendered as text.";
  readonly id: "commentTextNodes";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "commentAsText", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports distracting elements like <marquee> and <blink>.";
  readonly id: "distractingElements";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noDistractingElement", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports void DOM elements that have children, which is invalid HTML.";
  readonly id: "elementChildrenValidity";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "voidElementWithChildren", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports heading elements without accessible content.";
  readonly id: "headingContents";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyHeading", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports <html> elements without a lang prop.";
  readonly id: "htmlLangs";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingLang", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports <iframe> elements without a title prop.";
  readonly id: "iframeTitles";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingTitle", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports interactive elements with non-interactive ARIA roles.";
  readonly id: "interactiveElementRoles";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidRole", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports interactive elements that are not focusable via keyboard.";
  readonly id: "interactiveElementsFocusable";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "notFocusable", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports <label> elements without an associated control element.";
  readonly id: "labelAssociatedControls";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingAssociatedControl", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports invalid lang attribute values.";
  readonly id: "langValidity";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidLang", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports media elements without captions.";
  readonly id: "mediaCaptions";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingCaptions", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports mouse events without corresponding keyboard events.";
  readonly id: "mouseEventKeyEvents";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingKeyEvent", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports non-interactive elements with interactive event handlers.";
  readonly id: "nonInteractiveElementInteractions";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidHandler", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports non-interactive elements with interactive ARIA roles.";
  readonly id: "nonInteractiveElementRoles";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidRole", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports non-interactive elements with positive or zero tabIndex values.";
  readonly id: "nonInteractiveElementTabIndexes";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "nonInteractiveTabIndex", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports redundant ARIA roles on elements with implicit roles.";
  readonly id: "roleRedundancies";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "redundantRole", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports ARIA roles missing their required ARIA properties.";
  readonly id: "roleRequiredAriaProps";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingRequiredProps", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports ARIA properties that are not supported by an element's role.";
  readonly id: "roleSupportedAriaProps";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unsupportedProp", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports ARIA roles that have semantic HTML element equivalents.";
  readonly id: "roleTags";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferSemanticElement", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports scope props on non-th elements.";
  readonly id: "scopeProps";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidScope", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports static elements with event handlers that lack ARIA roles.";
  readonly id: "staticElementInteractions";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingRole", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports <svg> elements without a <title> child element.";
  readonly id: "svgTitles";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingTitle", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports positive tabIndex values.";
  readonly id: "tabIndexPositiveValues";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noPositiveTabIndex", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallow unescaped HTML entities in JSX text that may cause rendering issues.";
  readonly id: "unescapedEntities";
  readonly presets: readonly ["stylistic"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unescapedEntity", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallow unnecessary JSX fragments that wrap a single child or have no children.";
  readonly id: "unnecessaryFragments";
  readonly presets: readonly ["stylistic"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unnecessaryFragment", undefined>]>;
// #endregion