/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/rule-tester`
 */
// #region Interfaces
export interface InvalidTestCase<Options extends object | undefined = object | undefined> extends TestCase<Options> {
  output?: string;
  snapshot: string;
  suggestions?: TestSuggestion[];
}
export interface TestCase<Options extends object | undefined = object | undefined> {
  code: string;
  fileName?: string | undefined;
  files?: Record<string, string> | undefined;
  name?: string | undefined;
  only?: boolean;
  options?: Options | undefined;
  skip?: boolean;
}
export interface TestSuggestionFileCase {
  original: string;
  updated: string;
}
export interface TestSuggestionForFile {
  id: string;
  updated: string;
}
export interface TestSuggestionForFiles {
  files: Record<string, TestSuggestionFileCase[]>;
  id: string;
}
// #endregion

// #region Types
export type TestSuggestion = TestSuggestionForFile | TestSuggestionForFiles;
export type ValidTestCase<Options extends object | undefined> = string | ValidTestCaseObject<Options>;
export type ValidTestCaseObject<Options extends object | undefined> = TestCase<Options>;
// #endregion

// #region Classes
export declare class RuleTester {
  #private;
  constructor({
    assertNoLanguageReports,
    defaults,
    describe,
    diskBackedFSRoot,
    it,
    only,
    scope,
    skip
  }?: RuleTesterOptions);
  describe<OptionsSchema extends AnyOptionalSchema | undefined>(_: AnyRule<RuleAbout, OptionsSchema>, {
    invalid,
    valid
  }: TestCases<InferredInputObject<OptionsSchema>>): void;
}
// #endregion