/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/yaml-language`
 */
// #region Interfaces
export interface YamlFileServices {
  filePath: string;
  root: Root;
  sourceText: string;
}
// #endregion

// #region Types
export type YamlNodesByName = { [Node in yaml.YamlUnistNode as Node["type"]]: Node };
export type YamlNodeVisitors = WithExitKeys<YamlNodesByName>;
// #endregion

// #region Variables
export declare const yamlLanguage: Language<YamlNodeVisitors, YamlFileServices>;
// #endregion