/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/next`
 */
// #region Variables
export declare const next: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, []>;
// #endregion