/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/utils`
 */
// #region Types
export type PathKey = string & {
  readonly [PathKeyBrand]: true;
};
export type PromiseOrSync<T> = Promise<T> | T;
// #endregion

// #region Classes
export declare class FlintAssertionError extends Error {
  constructor(_: string);
}
// #endregion

// #region Functions
export declare function assert(_: unknown, _: string): asserts x;
export declare function dirnameKey(_: string, _: boolean): PathKey;
export declare function isTruthy<T extends NonNullable<unknown>>(_: null | T | undefined): value is T;
export declare function makeAbsolute(_: string): string;
export declare function normalizeDirname(_: string): string;
export declare function normalizePath(_: string): string;
export declare function nullThrows<T>(_: T, _: string): NonNullable<T>;
export declare function parseJsonSafe(_: string | undefined): unknown;
export declare function pathKey(_: string, _: boolean): PathKey;
// #endregion