/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/ts-patch`
 */
// #region Functions
export declare function setTSExtraSupportedExtensions(_: string[]): () => void;
export declare function setTSProgramCreationProxy(_: (_: typeof ts, _: typeof ts.createProgram) => typeof ts.createProgram): () => boolean;
// #endregion