/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/react`
 */
// #region Variables
export declare const react: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, []>;
// #endregion