/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/volar-language`
 */
// #region Types
export type VolarLanguage<FileServices extends object> = Language<TypeScriptNodesByName, Partial<FileServices> & TypeScriptFileServices>;
// #endregion

// #region Functions
export declare function createVolarBasedLanguage<FileServices extends object>(_: VolarLanguagePluginInitializer<FileServices>): VolarLanguage<FileServices>;
export declare function reportSourceCode<T extends string>(_: RuleContext<T>, _: RuleReport<T>): void;
// #endregion