/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/css-language`
 */
// #region Interfaces
export interface CssFileServices {
  root: CssNode;
  sourceText: string;
}
// #endregion

// #region Types
export type CssNodesByName = { [Node in CssNode as Node["type"]]: Node };
export type CssNodeVisitors = WithExitKeys<CssNodesByName>;
export type CssVisitorKey = CssNode["type"];
// #endregion

// #region Functions
export declare function getCssNodeRange(_: CssNode): CharacterReportRange;
// #endregion

// #region Variables
export declare const cssLanguage: Language<CssNodeVisitors, CssFileServices>;
// #endregion