/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/rule-data`
 */
// #region Interfaces
export interface RuleDetails extends AlternateLinterDetails {
  flint: FlintRuleReference;
  notes?: string;
}
// #endregion

// #region Types
export type FlintRuleReference = {
  name: string;
  plugin: FlintPlugin;
  preset?: FlintPreset;
  status?: "implemented";
  strictness?: "strict";
} | {
  name: string;
  plugin: FlintPlugin;
  status: "skipped";
};
export type LinterName = keyof typeof linterNames;
// #endregion

// #region Functions
export declare function getFlintRuleId(_: string, _: string): string;
export declare function getRuleForPlugin(_: string, _: string): AnyRule;
export declare function getRuleForPluginSafe(_: string, _: string): AnyRule | undefined;
// #endregion

// #region Variables
export declare const linterNames: {
  readonly biome: "Biome";
  readonly deno: "Deno";
  readonly eslint: "ESLint";
  readonly markdownlint: "Markdownlint";
  readonly oxlint: "Oxlint";
  readonly stylelint: "Stylelint";
};
export declare const ruleData: RuleDetails[];
// #endregion