/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/browser`
 */
// #region Variables
export declare const browser: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, [import("@flint.fyi/core").Rule<{
  readonly description: "Reports uses of the global alert/confirm/prompt dialog APIs.";
  readonly id: "alerts";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noAlert", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer using classList.toggle() over conditional classList.add() and classList.remove().";
  readonly id: "classListToggles";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferToggle", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports uses of `document.cookie` which can be error-prone and has security implications.";
  readonly id: "documentCookies";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noCookie", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports uses of `document.domain` which relaxes same-origin protections.";
  readonly id: "documentDomains";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noDomain", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports uses of `document.write()` and `document.writeln()` which block HTML parsing.";
  readonly id: "documentWrites";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noWrite", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer addEventListener over assigning to on* event handler properties.";
  readonly id: "eventListenerSubscriptions";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferAddEventListener", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prevents implicit global variable declarations in browser scripts.";
  readonly id: "implicitGlobals";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "implicitGlobal", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer KeyboardEvent.key over deprecated properties like keyCode, charCode, and which.";
  readonly id: "keyboardEventKeys";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferKey", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer modern DOM append/prepend methods over appendChild/insertBefore.";
  readonly id: "nodeAppendMethods";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferAppend" | "preferPrepend", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer using element.dataset over getAttribute/setAttribute for data-* attributes.";
  readonly id: "nodeDatasetAttributes";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferDataset", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer modern DOM APIs like .replaceWith() and .before() over legacy methods like .replaceChild() and .insertBefore().";
  readonly id: "nodeModificationMethods";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "after" | "append" | "before" | "prepend" | "replaceWith", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer modern `querySelector` and `querySelectorAll` over legacy DOM query methods.";
  readonly id: "nodeQueryMethods";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferQuerySelector", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer the modern `node.remove()` method over the legacy `parentNode.removeChild(node)` API.";
  readonly id: "nodeRemoveMethods";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferRemove", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer `textContent` over `innerText` for DOM nodes.";
  readonly id: "nodeTextContents";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferTextContent", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallow inline function expressions in removeEventListener calls.";
  readonly id: "removeEventListenerExpressions";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidRemoveEventListener", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports `javascript:` URLs that can act as a form of eval.";
  readonly id: "scriptUrls";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "scriptUrl", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Requires specifying the targetOrigin argument when calling window.postMessage().";
  readonly id: "windowMessagingTargetOrigin";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingTargetOrigin", undefined>]>;
// #endregion