/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/markdown-language`
 */
// #region Interfaces
export interface MarkdownFileServices {
  root: WithPosition<mdast.Root>;
}
export interface MarkdownNodesByName extends RootContentMapWithChildren {
  root: WithPosition<mdast.Root>;
}
export interface PointWithOffset extends Point {
  offset: number;
}
export interface PositionWithOffsets extends Position {
  end: PointWithOffset;
  start: PointWithOffset;
}
// #endregion

// #region Types
export type MarkdownNodeVisitors = WithExitKeys<MarkdownNodesByName>;
export type RootContentMapWithChildren = { [K in keyof mdast.RootContentMap]: WithPosition<mdast.RootContentMap[K]> };
export type WithPosition<T> = T & {
  position: PositionWithOffsets;
};
// #endregion

// #region Variables
export declare const markdownLanguage: Language<MarkdownNodeVisitors, MarkdownFileServices>;
// #endregion