/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/md`
 */
// #region Variables
export declare const md: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Reports bare URLs that should be formatted as autolinks or links.";
  readonly id: "bareUrls";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "bareUrl", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports definitions with empty URLs or only empty fragments.";
  readonly id: "definitionContents";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyDefinition", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports duplicate definition identifiers (case-insensitive).";
  readonly id: "definitionDuplicates";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "duplicateDefinition", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports unused reference definitions.";
  readonly id: "definitionUses";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unusedDefinition", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports fenced code blocks without a language specified.";
  readonly id: "fencedCodeLanguages";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingLanguage", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports heading levels incrementing by more than one.";
  readonly id: "headingIncrements";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "levelSkip", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports multiple H1 headings in the same document.";
  readonly id: "headingRootDuplicates";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "multipleH1", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports images without alternative text.";
  readonly id: "imageAltTexts";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingAlt" | "whitespaceAlt", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports images with empty URLs or only empty fragments.";
  readonly id: "imageContents";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyImage", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports missing label references.";
  readonly id: "labelReferences";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingLabel", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports invalid label references with whitespace.";
  readonly id: "labelReferenceValidity";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidWhitespace", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports links with empty URLs or only empty fragments.";
  readonly id: "linkContents";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyLink", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports link fragments that don't exist in the document.";
  readonly id: "linkFragments";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingFragment", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports reversed link and image syntax in Markdown.";
  readonly id: "mediaSyntaxReversals";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "reversedImage" | "reversedLink", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports resource links/images with URLs that match definition identifiers.";
  readonly id: "referenceLikeUrls";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "imageReferenceLike" | "linkReferenceLike", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports table rows with column counts that don't match the header.";
  readonly id: "tableColumnCounts";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "tooManyCells", undefined>]>;
// #endregion