/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/json`
 */
// #region Variables
export declare const json: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Reports unnecessary duplicate keys that override previous values.";
  readonly id: "keyDuplicates";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "duplicateKey", {
  allowKeys: import("zod/v4").ZodDefault<import("zod/v4").ZodArray<import("zod/v4").ZodString>>;
}>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports object keys that are not normalized using Unicode normalization forms.";
  readonly id: "keyNormalization";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unnormalizedKey", {
  form: import("zod/v4").ZodDefault<import("zod/v4").ZodEnum<{
    NFC: "NFC";
    NFD: "NFD";
    NFKC: "NFKC";
    NFKD: "NFKD";
  }>>;
}>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports JSON values that are unsafe for data interchange.";
  readonly id: "valueSafety";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "infinity" | "loneSurrogate" | "subnormal" | "unsafeInteger" | "unsafeZero", undefined>]>;
// #endregion