/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/solid`
 */
// #region Variables
export declare const solid: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, []>;
// #endregion