/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/json-language`
 */
// #region Types
export type JsonVisitorKey = AnyNode["type"];
// #endregion

// #region Functions
export declare function getNodeRange(_: AnyNode): CharacterReportRange;
export declare function getNodeText(_: ValueNode, _: string): string;
// #endregion

// #region Variables
export declare const jsonLanguage: Language<JsonNodeVisitors, JsonFileServices>;
// #endregion