/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/css`
 */
// #region Variables
export declare const css: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Reports hex colors with invalid values.";
  readonly id: "hexColorValidity";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalid", undefined>]>;
// #endregion