/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/astro`
 */
// #region Variables
export declare const astro: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Reports `client:only` directives without a value, or with a value whose type cannot be a renderer hint string.";
  readonly id: "clientOnlyDirectiveValues";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidValue" | "missingValue", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports using Astro's `set:html` directive, which injects content without escaping.";
  readonly id: "setHtmlDirectives";
  readonly presets: readonly ["security"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "setHtml", undefined>]>;
// #endregion