import path from "node:path";

import {
	SpanMap,
	SpanMapFeature,
	SpanMapKind,
} from "typescript-native/unstable/ast";
import { describe, expect, it } from "vitest";

import {
	createDiskBackedLinterHost,
	createVFSLinterHost,
} from "@flint.fyi/core";

import { vueLanguage } from "./index.ts";
import { createVueFileContext } from "./language.ts";

function createVueFile(sourceText: string) {
	const currentDirectory = import.meta.dirname;
	const filePath = path.join(currentDirectory, "fixture.vue");
	const host = createVFSLinterHost({
		baseHost: createDiskBackedLinterHost(currentDirectory),
	});
	host.vfsUpsertFile(
		path.join(currentDirectory, "tsconfig.json"),
		JSON.stringify({
			compilerOptions: {
				jsx: "preserve",
				noLib: true,
				noUnusedLocals: false,
			},
			files: ["fixture.vue"],
		}),
	);
	host.vfsUpsertFile(filePath, sourceText);
	const factory = vueLanguage.createFileFactory(host);
	const file = factory.createFile({
		filePath,
		filePathAbsolute: filePath,
		sourceText,
	});
	return { factory, file };
}

describe("Vize content mapper", () => {
	it.each([
		[
			'<template><div v-for="item in items" :key="item.id" /></template>',
			"item.id",
		],
		[
			'<template><div v-for="({ id }, index) in items" :key="id ?? index" /></template>',
			"id ?? index",
		],
		['<template><div v-for="親 in items" :key="親.id" /></template>', "親.id"],
		[
			'<template><div v-for="item in items"><div v-for="child in item.children" :key="child.id" /></div></template>',
			"child.id",
		],
		[
			'<template><div v-for="(item, index) in items" :key="(index => index)(0)" /></template>',
			"(index => index)(0)",
		],
	])("maps Vue references into canonical TSX: %s", (sourceText, key) => {
		const { factory, file } = createVueFile(sourceText);
		try {
			expect(file.services.sourceFile.fileName).toBe(
				path.join(import.meta.dirname, "fixture.vue"),
			);
			expect(file.services.sourceFile.text).toContain("Generated by vize");
			const spanMap = file.services.spanMap;
			expect(spanMap).toBeDefined();
			const keyBegin = sourceText.lastIndexOf(key);
			expect(
				spanMap?.originalToVirtualSpans(
					{ end: keyBegin + key.length, pos: keyBegin },
					SpanMapFeature.References,
				).length,
			).toBeGreaterThan(0);
		} finally {
			file[Symbol.dispose]();
			factory[Symbol.dispose]();
		}
	});

	it("exposes shorthand keys as atom mappings", () => {
		const sourceText =
			'<template><div v-for="item in items" :key /></template>';
		const { factory, file } = createVueFile(sourceText);
		try {
			const begin = sourceText.indexOf("key");
			const range = { end: begin + "key".length, pos: begin };
			expect(
				file.services.spanMap?.segments.some(
					(segment) =>
						segment.kind === SpanMapKind.Atom &&
						segment.originalStart === begin &&
						segment.originalEnd === begin + "key".length,
				),
			).toBe(true);
			expect(
				file.services.spanMap?.originalToVirtualSpans(
					range,
					SpanMapFeature.Hover,
				).length,
			).toBeGreaterThan(0);
			expect(
				file.services.spanMap?.originalToVirtualSpans(
					range,
					SpanMapFeature.References,
				).length,
			).toBeGreaterThan(0);
		} finally {
			file[Symbol.dispose]();
			factory[Symbol.dispose]();
		}
	});

	it("keeps duplicate original projections distinct and mappable", () => {
		const sourceText =
			'<template><div v-for="item in items" :key="item" /></template>';
		const { factory, file } = createVueFile(sourceText);
		try {
			const begin = sourceText.indexOf("key");
			const mappings = file.services.spanMap?.originalToVirtualSpans(
				{ end: begin + "key".length, pos: begin },
				SpanMapFeature.Hover,
			);
			expect(mappings).toHaveLength(2);
			expect(
				new Set(mappings?.map(({ range }) => `${range.pos}:${range.end}`)).size,
			).toBe(2);
			expect(
				mappings?.every((mapping) => SpanMap.isSingleSegment(mapping.fidelity)),
			).toBe(true);
		} finally {
			file[Symbol.dispose]();
			factory[Symbol.dispose]();
		}
	});

	it("returns a mapped file for malformed templates", () => {
		const { factory, file } = createVueFile(
			'<template><div v-for="item in items" :key="item"></template>',
		);
		try {
			expect(file.services.sourceFile.text).not.toBe("");
			expect(file.services.spanMap).toBeDefined();
			expect(vueLanguage.getLanguageReports?.(file)).toContainEqual(
				expect.objectContaining({ source: "vue" }),
			);
		} finally {
			file[Symbol.dispose]();
			factory[Symbol.dispose]();
		}
	});

	it("preserves directive validation reports", () => {
		expect(
			createVueFileContext("file.vue", "<!-- flint-other * --><template />")
				.reports,
		).toMatchObject([
			{
				about: { id: "commentDirectiveUnknown" },
			},
		]);
	});
});
