/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/node`
 */
// #region Variables
export declare const node: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, [import("@flint.fyi/core").Rule<{
  readonly description: "Prefer strict assertion mode from Node.js for better error messages and behavior.";
  readonly id: "assertStrict";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferStrictAssert", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer `assert.ok()` over `assert()` for explicit intent and better readability.";
  readonly id: "assertStyles";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferAssertOk", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer direct Blob reading methods over wrapping in Response for simpler code.";
  readonly id: "blobReadingMethods";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferBlobMethod", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer modern Buffer allocation methods over the deprecated Buffer constructor.";
  readonly id: "bufferAllocators";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "useBufferAllocators", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallow leading or trailing spaces in console method string arguments.";
  readonly id: "consoleSpaces";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "leading" | "trailing", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer EventTarget over EventEmitter for cross-platform compatibility.";
  readonly id: "eventClasses";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferEventTarget", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prevent assignment to the `exports` variable in CommonJS modules.";
  readonly id: "exportsAssignments";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noExportsAssign", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer `import.meta.dirname` and `import.meta.filename` over legacy file path techniques.";
  readonly id: "filePathsFromImportMeta";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferImportMetaDirname" | "preferImportMetaFilename", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer reading JSON files as buffers when using JSON.parse for better performance.";
  readonly id: "fileReadJSONBuffers";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferBufferReading", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer the `node:` protocol prefix for Node.js built-in modules for clarity and consistency.";
  readonly id: "nodeProtocols";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferNodeProtocol", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prevent direct use of `process.exit()` for better error handling and testing.";
  readonly id: "processExits";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noProcessExit", undefined>]>;
// #endregion