/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/vue`
 */
// #region Variables
export declare const vue: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Reports v-for directives without a valid key binding.";
  readonly id: "vForKeys";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "invalidKey" | "missingKey" | "staticKey", undefined>]>;
// #endregion