/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/performance`
 */
// #region Variables
export declare const performance: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, [import("@flint.fyi/core").Rule<{
  readonly description: "Reports using the delete operator.";
  readonly id: "deletes";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noDelete", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallow computed member access on imported namespace identifiers.";
  readonly id: "importedNamespaceDynamicAccesses";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noDynamicAccess", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports using await expressions inside loops.";
  readonly id: "loopAwaits";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noAwaitInLoop", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports function declarations and expressions inside loops that reference variables modified by the loop.";
  readonly id: "loopFunctions";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noFunctionInLoop", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports spread operations that accumulate values in loops, causing quadratic time complexity.";
  readonly id: "spreadAccumulators";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "noAccumulatingSpread", undefined>]>;
// #endregion