/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/plugin-flint`
 */
// #region Variables
export declare const flint: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, [import("@flint.fyi/core").Rule<{
  readonly description: "Requires passing `sourceFile` to `getStart()` for better performance.";
  readonly id: "getStartSourceFile";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingSourceFile", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports cases for invalid code that isn't formatted across lines.";
  readonly id: "invalidCodeLines";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "singleLineTest", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports `context.report()` calls missing data for message placeholders.";
  readonly id: "missingPlaceholders";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "missingPlaceholders", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Disallows using the `in` operator to check properties on TypeScript nodes.";
  readonly id: "nodePropertyInChecks";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "nodePropertyInChecks", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports and auto-fixes message placeholders that are not formatted as `{{ placeholder }}`.";
  readonly id: "placeholderFormats";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "placeholderFormats", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports Flint plugin `rules` arrays that are not sorted alphabetically.";
  readonly id: "pluginRuleOrdering";
  readonly presets: readonly ["stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "pluginRuleOrdering", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports plugin rules created directly with language instead of through RuleCreator.";
  readonly id: "ruleCreationMethods";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "ruleCreationMethods", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports test cases that are identical to previous test cases.";
  readonly id: "testCaseDuplicates";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "duplicateTest", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports test cases that have the same name as a previous test case.";
  readonly id: "testCaseNameDuplicates";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "duplicateTestName", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Test case code should be a static string literal.";
  readonly id: "testCaseNonStaticCode";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "nonStaticTestCaseCode", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports test cases that are marked `only: true`.";
  readonly id: "testCaseOnlyFlags";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "testCaseOnly", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Test cases with only a code property can use string shorthand syntax instead of object literal syntax.";
  readonly id: "testShorthands";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "testShorthands", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports message IDs defined in the messages object that are never used in recognized report calls.";
  readonly id: "unusedMessageIds";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "unusedMessageIds", undefined>]>;
// #endregion