/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/core`
 */
// #region Interfaces
export interface BaseAbout {
  readonly id: string;
}
export interface CacheStorage {
  configs: Record<string, number>;
  files: Record<string, FileCacheStorage>;
  globalInvalidations: GlobalInvalidation[];
}
export interface ChangeBase {
  id: string;
}
export interface CharacterReportRange {
  begin: number;
  end: number;
}
export interface ColumnAndLine extends ColumnAndLineWithoutRaw {
  raw: number;
}
export interface ColumnAndLineWithoutRaw {
  column: number;
  line: number;
}
export interface CommentDirective {
  range: NormalizedReportRangeObject;
  selections: string[];
  type: CommentDirectiveType;
}
export interface CommentDirectiveWithinFile extends CommentDirective {
  type: CommentDirectiveTypeWithinFile;
}
export interface Config {
  definition: ConfigDefinition;
  isFlintConfig: true;
}
export interface ConfigDefinition {
  cacheLocation?: string;
  from?: string;
  ignore?: string[];
  projects?: string[];
  use: ConfigUseDefinition[];
}
export interface ConfigRuleDefinitionObject {
  options: boolean | object;
  rule: AnyRule;
}
export interface ConfigUseDefinition {
  files: AnyLevelDeep<FilesValue>;
  rules: AnyLevelDeep<ConfigRuleDefinition>;
}
export interface DirectiveCollection {
  directives: CommentDirective[];
  reports: FileReport[];
}
export interface FileAboutData {
  filePath: string;
  filePathAbsolute: string;
  sourceText: string;
}
export interface FileCacheImpacts {
  dependencies?: string[];
}
export interface FileCacheStorage extends FileCacheImpacts {
  languageReports?: LanguageReport[];
  reports?: FileReport[];
  timestamp: number;
}
export interface FileChange {
  range: CharacterReportRange;
  text: string;
}
export interface FileReport extends NormalizedReport {
  about: FileReportAbout;
}
export interface FileReportAbout extends BaseAbout {
  url?: string;
}
export interface FileReportWithFix extends FileReport {
  fix: Fix[];
}
export interface FileResults {
  dependencies: Set<string>;
  languageReports: LanguageReport[];
  reports: FileReport[];
}
export interface FormattingResults {
  clean: Set<string>;
  dirty: Set<string>;
  written: boolean;
}
export interface HasGetLineAndCharacterOfPosition {
  getLineAndCharacterOfPosition(_: number): TSLineAndCharacter;
}
export interface Language<AstNodesByName, FileServices extends object> extends LanguageDefinition<AstNodesByName, FileServices> {
  createFileFactory(_: LinterHost): LanguageFileFactory<FileServices>;
  createRule: LanguageCreateRule<AstNodesByName, FileServices>;
  getFileCacheImpacts?(_: LanguageFile<FileServices>): LanguageFileCacheImpacts;
  getLanguageReports?(_: LanguageFile<FileServices>): LanguageReports;
  runFileVisitors<OptionsSchema extends AnyOptionalSchema | undefined = AnyOptionalSchema | undefined>(_: LanguageFile<FileServices>, _: InferredOutputObject<OptionsSchema>, _: RuleRuntime<AstNodesByName, FileServices>): void;
}
export interface LanguageAbout {
  name: string;
}
export interface LanguageDefinition<AstNodesByName, FileServices extends object> {
  about: LanguageAbout;
  createFileFactory(_: LinterHost): LanguageFileFactoryDefinition<FileServices>;
  getFileCacheImpacts?(_: LanguageFile<FileServices>): LanguageFileCacheImpacts;
  getLanguageReports?(_: LanguageFile<FileServices>): LanguageReports;
  orderFilePaths?(_: readonly string[], _: LinterHost): string[];
  runFileVisitors<OptionsSchema extends AnyOptionalSchema | undefined = AnyOptionalSchema | undefined>(_: LanguageFile<FileServices>, _: InferredOutputObject<OptionsSchema>, _: RuleRuntime<AstNodesByName, FileServices>): void;
}
export interface LanguageFileBase<FileServices extends object> {
  about: FileAboutData;
  adjustReportRange?: (_: CharacterReportRange) => CharacterReportRange | null;
  directives?: CommentDirective[];
  reports?: FileReport[];
  services: FileServices;
}
export interface LanguageFileCacheImpacts {
  dependencies: string[];
  invalidatesCache: boolean;
}
export interface LanguageFileFactory<FileServices extends object> {
  createFile(_: FileAboutData): LanguageFile<FileServices>;
}
export interface LanguageFileFactoryDefinition<FileServices extends object> {
  createFile(_: FileAboutData): LanguageFileDefinition<FileServices>;
}
export interface LanguageReport {
  code?: string;
  range?: CharacterReportRange;
  source?: string;
  text: string;
}
export interface LinterHost {
  fileTypeSync(_: string): "directory" | "file" | undefined;
  getCurrentDirectory(): string;
  getFileTouchTime(_: string): Promise<number | undefined>;
  getFileTouchTimeSync(_: string): number | undefined;
  getRepositoryRoot(): string | undefined;
  glob(_: string[], _: LinterHostGlobOptions): Promise<string[]>;
  isCaseSensitiveFS(): boolean;
  readDirectory(_: string): Promise<LinterHostDirectoryEntry[]>;
  readDirectorySync(_: string): LinterHostDirectoryEntry[];
  readFile(_: string): Promise<string | undefined>;
  readFileSync(_: string): string | undefined;
  watchDirectorySync(_: string, _: LinterHostDirectoryWatcher, _: WatchDirectoryOptions): Disposable;
  watchFileSync(_: string, _: LinterHostFileWatcher, _: WatchOptions): Disposable;
  writeFile(_: string, _: string): Promise<void>;
  writeFileSync(_: string, _: string): void;
}
export interface LinterHostDirectoryEntry {
  name: string;
  type: "directory" | "file";
}
export interface LintResults {
  allFilePaths: Set<string>;
  allFileResults: Map<string, FinalizedFileResults>;
  cached: Map<string, FileCacheStorage> | undefined;
  ruleCount: number;
}
export interface LintResultsMaybeWithChanges extends LintResults {
  changed?: Set<string>;
}
export interface LintResultsWithChanges extends LintResults {
  changed: Set<string>;
}
export interface NormalizedReport {
  data?: ReportInterpolationData | undefined;
  dependencies?: string[];
  fix?: Fix[] | undefined;
  message: ReportMessageData;
  range: NormalizedReportRangeObject;
  suggestions?: Suggestion[] | undefined;
}
export interface NormalizedReportRangeObject {
  begin: ColumnAndLine;
  end: ColumnAndLine;
}
export interface Plugin<About extends RuleAbout, FilesKey extends string | undefined, Rules extends AnyRule<About>[]> {
  files: undefined extends FilesKey ? undefined : Record<FilesKey & string, FilesValue>;
  name: string;
  presets: PluginPresets<Rules>;
  rules: PluginRulesFactory<Rules>;
  rulesById: Map<string, Rules[number]>;
}
export interface ReportMessageData {
  primary: string;
  secondary: string[];
  suggestions: string[];
}
export interface ResolvedChange extends FileChange {
  filePath: string;
}
export interface Rule<About extends RuleAbout, MessageId extends string, OptionsSchema extends AnyOptionalSchema | undefined> extends RuleDefinition<About, object, object, MessageId, OptionsSchema> {
  language: AnyLanguage;
}
export interface RuleAbout<Presets extends string = string> extends BaseAbout {
  readonly description: string;
  readonly pluginId?: string;
  readonly presets?: readonly Presets[];
}
export interface RuleContext<MessageId extends string> {
  host: LinterHost;
  report: RuleReporter<MessageId>;
}
export interface RuleCreatorOptions<Presets extends string> {
  docs: (_: string) => string;
  pluginId: string;
  presets: readonly Presets[];
}
export interface RuleDefinition<About extends RuleAbout, AstNodesByName, FileServices extends object, MessageId extends string, OptionsSchema extends AnyOptionalSchema | undefined> {
  about: About;
  messages: Record<MessageId, ReportMessageData>;
  options?: OptionsSchema;
  setup: RuleSetup<AstNodesByName, FileServices, MessageId, InferredOutputObject<OptionsSchema>>;
}
export interface RuleReport<Message extends string = string> {
  data?: ReportInterpolationData | undefined;
  dependencies?: string[];
  filePath?: string;
  fix?: Fix | Fix[] | undefined;
  message: Message;
  suggestions?: Suggestion[] | undefined;
  range: CharacterReportRange;
}
export interface RuleRuntime<AstNodesByName, FileServices extends object> {
  dependencies?: string[];
  teardown?: RuleTeardown;
  visitors?: RuleVisitors<AstNodesByName, FileServices>;
}
export interface SourceFileWithLineMap {
  readonly text: string;
  lineMap?: readonly number[];
}
export interface SourceFileWithLineMapAndFileName extends SourceFileWithLineMap {
  fileName: string;
}
export interface SuggestionForFiles extends ChangeBase {
  files: Partial<Record<string, FileChange[]>>;
}
export interface TSLineAndCharacter {
  character: number;
  line: number;
}
export interface VFSLinterHost extends LinterHost {
  vfsDeleteFile(_: string): void;
  vfsListFiles(): ReadonlyMap<string, string>;
  vfsUpsertFile(_: string, _: string): void;
}
export interface WatchDirectoryOptions extends WatchOptions {
  recursive: boolean;
}
export interface WatchOptions {
  ignoredPaths: string[];
  pollingInterval?: number;
}
// #endregion

// #region Types
export type AnyLanguage = Language<object, object>;
export type AnyLanguageFile = LanguageFile<object>;
export type AnyLanguageFileFactory = LanguageFileFactory<object>;
export type AnyOptionalSchema = Record<string, z.$ZodDefault | z.$ZodOptional>;
export type AnyRule<About extends RuleAbout = RuleAbout, OptionsSchema extends AnyOptionalSchema | undefined = AnyOptionalSchema | undefined> = Rule$1<About, string, OptionsSchema>;
export type AnyRuleDefinition<OptionsSchema extends AnyOptionalSchema | undefined = AnyOptionalSchema | undefined> = RuleDefinition<RuleAbout, unknown, object, string, OptionsSchema>;
export type Change = Fix | Suggestion;
export type CommentDirectiveType = "disable-file" | CommentDirectiveTypeWithinFile;
export type CommentDirectiveTypeWithinFile = "disable-lines-begin" | "disable-lines-end" | "disable-next-line";
export type ConfigRuleDefinition = AnyRule | ConfigRuleDefinitionObject;
export type CreateVFSLinterHostOpts = {
  baseHost: LinterHost;
  caseSensitive?: never;
  cwd?: string | undefined;
} | {
  baseHost?: never;
  caseSensitive?: boolean | undefined;
  cwd: string;
};
export type Fix = FileChange;
export type GetLanguageAstNodesByName<InputLanguage extends AnyLanguage> = InputLanguage extends Language<infer AstNodesByName, infer _> ? AstNodesByName : never;
export type GetLanguageFileServices<InputLanguage extends AnyLanguage> = InputLanguage extends Language<infer _, infer FileServices> ? FileServices : never;
export type InferredInputObject<OptionsSchema extends AnyOptionalSchema | undefined> = OptionsSchema extends AnyOptionalSchema ? z.input<OptionalObjectSchema<OptionsSchema>> : undefined;
export type InferredOutputObject<OptionsSchema extends AnyOptionalSchema | undefined> = OptionsSchema extends AnyOptionalSchema ? z.output<OptionalObjectSchema<OptionsSchema>> : undefined;
export type LanguageCreateRule<AstNodesByName, FileServices extends object> = <const About extends RuleAbout, const MessageId extends string, OptionsSchema extends AnyOptionalSchema | undefined = undefined>(_: RuleDefinition<About, AstNodesByName, FileServices, MessageId, OptionsSchema>) => Rule$1<About, MessageId, OptionsSchema>;
export type LanguageFile<FileServices extends object> = Disposable & LanguageFileBase<FileServices>;
export type LanguageFileDefinition<FileServices extends object> = LanguageFileBase<FileServices> & Partial<Disposable>;
export type LanguageReports = LanguageReport[];
export type LinterHostDirectoryWatcher = (_: string) => void;
export type LinterHostFileWatcher = (_: LinterHostFileWatcherEvent) => void;
export type LinterHostFileWatcherEvent = "changed" | "created" | "deleted";
export type MessageForContext<Context extends RuleContext<never>> = Context extends RuleContext<infer MessageId> ? MessageId : never;
export type OptionalObjectSchema<OptionsSchema extends AnyOptionalSchema> = z.$ZodObject<OptionsSchema, z.$strict> & z.$ZodType<Record<string, unknown>, Record<string, unknown>, z.$ZodObjectInternals<OptionsSchema, z.$strict>>;
export type PluginPresets<Rules extends AnyRule[]> = Record<PluginPresetName<Rules>, Rules[number][]>;
export type PluginRulesFactory<Rules extends AnyRule[]> = (_: PluginRulesOptions<Rules>) => PluginConfiguredRules<Rules>;
export type ReportInterpolationData = Record<string, boolean | number | string>;
export type RuleReporter<MessageId extends string> = (_: RuleReport<MessageId>) => void;
export type RuleSetup<AstNodesByName, FileServices extends object, MessageId extends string, Options extends Record<string, unknown> | undefined> = (_: RuleContext<MessageId>) => PromiseOrSync<RuleRuntime<AstNodesByName, FileServices & {
  options: Options;
}> | undefined>;
export type RuleTeardown = () => PromiseOrSync<undefined>;
export type RuleVisitor<ASTNode, VisitorServices extends object> = (_: ASTNode, _: VisitorServices) => void;
export type RuleVisitors<AstNodesByName, VisitorServices extends object> = { [Kind in keyof AstNodesByName]?: RuleVisitor<AstNodesByName[Kind], VisitorServices> };
export type RunMode = "single-run" | "watch";
export type Suggestion = SuggestionForFile | SuggestionForFiles;
export type SuggestionForFile = ChangeBase & FileChange;
export type WithExitKeys<T> = Simplify<T & { [K in keyof T & string as `${K}:exit`]: T[K] }>;
// #endregion

// #region Classes
export declare class DirectivesCollector {
  #private;
  constructor(_: number);
  add(_: NormalizedReportRangeObject, _: string, _: string): void;
  collect(): DirectiveCollection;
}
export declare class RuleCreator<Presets extends string, const About extends RuleAbout = RuleAbout<Presets>> {
  #private;
  constructor(_: RuleCreatorOptions<Presets>);
  createRule<const RuleDefinitionAbout extends About, const Language extends AnyLanguage, const MessageId extends string, OptionsSchema extends AnyOptionalSchema | undefined = undefined>(_: Language, _: RuleDefinition<ExactObject<RuleDefinitionAbout, About>, GetLanguageAstNodesByName<Language>, GetLanguageFileServices<Language>, MessageId, OptionsSchema>): Rule$1<RuleDefinitionAbout & {
    readonly pluginId: string;
    readonly url: string;
  }, MessageId, OptionsSchema>;
}
// #endregion

// #region Functions
export declare function applyChangesToText(_: FileChange[], _: string): string;
export declare function binarySearch<T>(_: readonly T[], _: (_: T) => number, _?: "no-fallback"): undefined | {
  element: T;
  index: number;
};
export declare function binarySearch<T>(_: readonly T[], _: (_: T) => number, _: "fallback-next" | "fallback-prev"): {
  element: T | undefined;
  index: number;
};
export declare function createDiskBackedLinterHost(_: string): LinterHost;
export declare function createEphemeralLinterHost(_: LinterHost): LinterHost;
export declare function createLanguage<AstNodesByName, FileServices extends object = object>(_: LanguageDefinition<AstNodesByName, FileServices>): Language<AstNodesByName, FileServices>;
export declare function createPlugin<const About extends RuleAbout, const FilesKey extends string | undefined, const Rules extends UnsafeAnyRule<About>[]>({
  files,
  name,
  rules
}: CreatePluginOptions<About, FilesKey, Rules>): Plugin<About, FilesKey, Rules>;
export declare function createVFSLinterHost(_: CreateVFSLinterHostOpts): VFSLinterHost;
export declare function defineConfig(_: ConfigDefinition): Config;
export declare function findConfigFileName(_: LinterHost): Promise<string | undefined>;
export declare function formatReport(_: ReportInterpolationData | undefined, _: string): string;
export declare function getColumnAndLineOfPosition(_: HasGetLineAndCharacterOfPosition | SourceFileWithLineMap | string, _: number): ColumnAndLine;
export declare function getPositionOfColumnAndLine(_: SourceFileWithLineMap | string, _: ColumnAndLineWithoutRaw): number;
export declare function hasFix(_: FileReport): report is FileReportWithFix;
export declare function isConfig(_: unknown): value is Config;
export declare function isFileSystemCaseSensitive(): boolean;
export declare function isSuggestionForFiles(_: Change): change is SuggestionForFiles;
export declare function parseOptions<OptionsSchema extends AnyOptionalSchema | undefined>(_: OptionsSchema, _: InferredInputObject<OptionsSchema>): InferredOutputObject<OptionsSchema>;
export declare function processRuleReport(_: AnyLanguageFile, _: AnyRule, _: RuleReport): FileReport | null;
export declare function runConfig(_: ProcessedConfigDefinition, _: LinterHost, {
  cacheLocation: cacheLocationFromCli,
  ignoreCache,
  skipCacheWrite,
  skipLanguageReports
}: RunConfigOptions): Promise<LintResults>;
export declare function runConfigFixing(_: ProcessedConfigDefinition, _: LinterHost, {
  cacheLocation,
  ignoreCache,
  requestedSuggestions,
  skipLanguageReports
}: RunConfigFixingOptions): Promise<LintResultsWithChanges>;
export declare function runLintRule(_: AnyRule, _: LanguageFilesWithOptions[], _: LinterHost): Promise<Map<string, FileReport[]>>;
export declare function validateConfigDefinition(_: ConfigDefinition, _: string): string | undefined;
export declare function writeToCache(_: LinterHost, _: string, _: LintResults, _: string | undefined): Promise<void>;
// #endregion

// #region Variables
export declare const commonlyIgnoredPaths: string[];
export declare const configFileNameCandidates: string[];
export declare const directiveReports: DirectiveReports;
export declare const getCacheFilePath: (userProvidedCacheLocation?: string) => string;
export declare const gitVcs: string;
export declare const globs: Globs;
export declare const jjVcs: string;
export declare const nodeModulesCache: string;
export declare const nodeModulesDir: string;
export declare const vcsDirectories: string[];
// #endregion