/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/text-language`
 */
// #region Interfaces
export interface TextFileServices {
  filePath: string;
  filePathAbsolute: string;
  sourceText: string;
}
export interface TextNodes {
  file: string;
  line: string;
}
// #endregion

// #region Variables
export declare const textLanguage: Language<TextNodes, TextFileServices>;
// #endregion