// Generated by scripts/generate-ast.ts. Do not edit.
/* eslint-disable perfectionist/sort-modules, perfectionist/sort-union-types */
import type * as NativeAST from "typescript-native/unstable/ast";

export type AbstractKeyword = NativeAST.AbstractKeyword;
export type AccessExpression = NativeAST.AccessExpression;
export type AccessorDeclaration = NativeAST.AccessorDeclaration;
export type AccessorKeyword = NativeAST.AccessorKeyword;
export type AdditiveOperator = NativeAST.AdditiveOperator;
export type AdditiveOperatorOrHigher = NativeAST.AdditiveOperatorOrHigher;
export type AnyImportSyntax = NativeAST.AnyImportSyntax;
export type ArgumentList = NativeAST.ArgumentList;
export type ArrayBindingElement = NativeAST.ArrayBindingElement;
export type ArrayBindingPattern = NativeAST.ArrayBindingPattern;
export type ArrayDestructuringAssignment =
	NativeAST.ArrayDestructuringAssignment;
export type ArrayLiteralExpression = NativeAST.ArrayLiteralExpression;
export type ArrayTypeNode = NativeAST.ArrayTypeNode;
export type ArrowFunction = NativeAST.ArrowFunction;
export type AsExpression = NativeAST.AsExpression;
export type AssertKeyword = NativeAST.AssertKeyword;
export type AssertionExpression = NativeAST.AssertionExpression;
export type AssertsKeyword = NativeAST.AssertsKeyword;
export type AssignmentOperator = NativeAST.AssignmentOperator;
export type AssignmentOperatorOrHigher = NativeAST.AssignmentOperatorOrHigher;
export type AssignmentOperatorToken = NativeAST.AssignmentOperatorToken;
export type AsteriskToken = NativeAST.AsteriskToken;
export type AsyncKeyword = NativeAST.AsyncKeyword;
export type AwaitExpression = NativeAST.AwaitExpression;
export type AwaitKeyword = NativeAST.AwaitKeyword;
export type BigIntLiteral = NativeAST.BigIntLiteral;
export type BinaryExpression = NativeAST.BinaryExpression;
export type BinaryOperator = NativeAST.BinaryOperator;
export type BinaryOperatorToken = NativeAST.BinaryOperatorToken;
export type BindingElement = NativeAST.BindingElement;
export type BindingElementList = NativeAST.BindingElementList;
export type BindingName = NativeAST.BindingName;
export type BindingPattern = NativeAST.BindingPattern;
export type BitwiseOperator = NativeAST.BitwiseOperator;
export type BitwiseOperatorOrHigher = NativeAST.BitwiseOperatorOrHigher;
export type Block = NativeAST.Block;
export type BlockOrExpression = NativeAST.BlockOrExpression;
export type BooleanLiteral = NativeAST.BooleanLiteral;
export type BreakOrContinueStatement = NativeAST.BreakOrContinueStatement;
export type BreakStatement = NativeAST.BreakStatement;
export type CallExpression = NativeAST.CallExpression;
export type CallLikeExpression = NativeAST.CallLikeExpression;
export type CallOrNewExpression = NativeAST.CallOrNewExpression;
export type CallSignatureDeclaration = NativeAST.CallSignatureDeclaration;
export type CaseBlock = NativeAST.CaseBlock;
export type CaseClause = NativeAST.CaseClause;
export type CaseClausesList = NativeAST.CaseClausesList;
export type CaseKeyword = NativeAST.CaseKeyword;
export type CaseOrDefaultClause = NativeAST.CaseOrDefaultClause;
export type CatchClause = NativeAST.CatchClause;
export type ClassDeclaration = NativeAST.ClassDeclaration;
export type ClassElementList = NativeAST.ClassElementList;
export type ClassExpression = NativeAST.ClassExpression;
export type ClassLikeDeclaration = NativeAST.ClassLikeDeclaration;
export type ClassStaticBlockDeclaration = NativeAST.ClassStaticBlockDeclaration;
export type ColonToken = NativeAST.ColonToken;
export type CompoundAssignmentOperator = NativeAST.CompoundAssignmentOperator;
export type ComputedPropertyName = NativeAST.ComputedPropertyName;
export type ConciseBody = NativeAST.ConciseBody;
export type ConditionalExpression = NativeAST.ConditionalExpression;
export type ConditionalTypeNode = NativeAST.ConditionalTypeNode;
export type ConstKeyword = NativeAST.ConstKeyword;
export type ConstructSignatureDeclaration =
	NativeAST.ConstructSignatureDeclaration;
export type ConstructorDeclaration = NativeAST.ConstructorDeclaration;
export type ConstructorTypeNode = NativeAST.ConstructorTypeNode;
export type ContinueStatement = NativeAST.ContinueStatement;
export type DebuggerStatement = NativeAST.DebuggerStatement;
export type DeclarationName = NativeAST.DeclarationName;
export type DeclareKeyword = NativeAST.DeclareKeyword;
export type Decorator = NativeAST.Decorator;
export type DefaultClause = NativeAST.DefaultClause;
export type DefaultKeyword = NativeAST.DefaultKeyword;
export type DeleteExpression = NativeAST.DeleteExpression;
export type DestructuringAssignment = NativeAST.DestructuringAssignment;
export type DoStatement = NativeAST.DoStatement;
export type DotDotDotToken = NativeAST.DotDotDotToken;
export type DotToken = NativeAST.DotToken;
export type ElementAccessExpression = NativeAST.ElementAccessExpression;
export type ElementList = NativeAST.ElementList;
export type EmptyStatement = NativeAST.EmptyStatement;
export type EndOfFile = NativeAST.EndOfFile;
export type EntityName = NativeAST.EntityName;
export type EntityNameExpression = NativeAST.EntityNameExpression;
export type EntityNameOrEntityNameExpression =
	NativeAST.EntityNameOrEntityNameExpression;
export type EnumDeclaration = NativeAST.EnumDeclaration;
export type EnumMember = NativeAST.EnumMember;
export type EnumMemberList = NativeAST.EnumMemberList;
export type EqualityOperator = NativeAST.EqualityOperator;
export type EqualityOperatorOrHigher = NativeAST.EqualityOperatorOrHigher;
export type EqualsGreaterThanToken = NativeAST.EqualsGreaterThanToken;
export type EqualsToken = NativeAST.EqualsToken;
export type ExclamationToken = NativeAST.ExclamationToken;
export type ExponentiationOperator = NativeAST.ExponentiationOperator;
export type ExportAssignment = NativeAST.ExportAssignment;
export type ExportDeclaration = NativeAST.ExportDeclaration;
export type ExportKeyword = NativeAST.ExportKeyword;
export type ExportSpecifier = NativeAST.ExportSpecifier;
export type ExportSpecifierList = NativeAST.ExportSpecifierList;
export type ExpressionStatement = NativeAST.ExpressionStatement;
export type ExpressionWithTypeArguments = NativeAST.ExpressionWithTypeArguments;
export type ExpressionWithTypeArgumentsList =
	NativeAST.ExpressionWithTypeArgumentsList;
export type ExternalModuleReference = NativeAST.ExternalModuleReference;
export type FalseLiteral = NativeAST.FalseLiteral;
export type FileReference = NativeAST.FileReference;
export type ForInOrOfStatement = NativeAST.ForInOrOfStatement;
export type ForInStatement = NativeAST.ForInStatement;
export type ForInitializer = NativeAST.ForInitializer;
export type ForOfStatement = NativeAST.ForOfStatement;
export type ForStatement = NativeAST.ForStatement;
export type FunctionBody = NativeAST.FunctionBody;
export type FunctionDeclaration = NativeAST.FunctionDeclaration;
export type FunctionExpression = NativeAST.FunctionExpression;
export type FunctionLikeDeclaration = NativeAST.FunctionLikeDeclaration;
export type FunctionTypeNode = NativeAST.FunctionTypeNode;
export type GetAccessorDeclaration = NativeAST.GetAccessorDeclaration;
export type HasExpression = NativeAST.HasExpression;
export type HasExpressionInitializer = NativeAST.HasExpressionInitializer;
export type HasIllegalExpressionInitializer =
	NativeAST.HasIllegalExpressionInitializer;
export type HasInitializer = NativeAST.HasInitializer;
export type HeritageClause = NativeAST.HeritageClause;
export type HeritageClauseElement = NativeAST.HeritageClauseElement;
export type HeritageClauseElementList = NativeAST.HeritageClauseElementList;
export type HeritageClauseList = NativeAST.HeritageClauseList;
export type Identifier = NativeAST.Identifier;
export type IfStatement = NativeAST.IfStatement;
export type ImportAttribute = NativeAST.ImportAttribute;
export type ImportAttributeList = NativeAST.ImportAttributeList;
export type ImportAttributeName = NativeAST.ImportAttributeName;
export type ImportAttributes = NativeAST.ImportAttributes;
export type ImportClause = NativeAST.ImportClause;
export type ImportClauseOrBindingPattern =
	NativeAST.ImportClauseOrBindingPattern;
export type ImportDeclaration = NativeAST.ImportDeclaration;
export type ImportEqualsDeclaration = NativeAST.ImportEqualsDeclaration;
export type ImportExpression = NativeAST.ImportExpression;
export type ImportPhaseModifierSyntaxKind =
	NativeAST.ImportPhaseModifierSyntaxKind;
export type ImportSpecifier = NativeAST.ImportSpecifier;
export type ImportSpecifierList = NativeAST.ImportSpecifierList;
export type ImportTypeNode = NativeAST.ImportTypeNode;
export type InKeyword = NativeAST.InKeyword;
export type IncrementExpression = NativeAST.IncrementExpression;
export type IndexSignatureDeclaration = NativeAST.IndexSignatureDeclaration;
export type IndexedAccessTypeNode = NativeAST.IndexedAccessTypeNode;
export type InferTypeNode = NativeAST.InferTypeNode;
export type InterfaceDeclaration = NativeAST.InterfaceDeclaration;
export type IntersectionTypeNode = NativeAST.IntersectionTypeNode;
export type JSDoc = NativeAST.JSDoc;
export type JSDocAllType = NativeAST.JSDocAllType;
export type JSDocAugmentsTag = NativeAST.JSDocAugmentsTag;
export type JSDocCallbackTag = NativeAST.JSDocCallbackTag;
export type JSDocDeprecatedTag = NativeAST.JSDocDeprecatedTag;
export type JSDocFullName = NativeAST.JSDocFullName;
export type JSDocImplementsTag = NativeAST.JSDocImplementsTag;
export type JSDocImportTag = NativeAST.JSDocImportTag;
export type JSDocLink = NativeAST.JSDocLink;
export type JSDocLinkCode = NativeAST.JSDocLinkCode;
export type JSDocLinkPlain = NativeAST.JSDocLinkPlain;
export type JSDocNameReference = NativeAST.JSDocNameReference;
export type JSDocNodeSyntaxKind = NativeAST.JSDocNodeSyntaxKind;
export type JSDocNonNullableType = NativeAST.JSDocNonNullableType;
export type JSDocNullableType = NativeAST.JSDocNullableType;
export type JSDocOptionalType = NativeAST.JSDocOptionalType;
export type JSDocOverloadTag = NativeAST.JSDocOverloadTag;
export type JSDocOverrideTag = NativeAST.JSDocOverrideTag;
export type JSDocParameterOrPropertyTag = NativeAST.JSDocParameterOrPropertyTag;
export type JSDocParameterTag = NativeAST.JSDocParameterTag;
export type JSDocPrivateTag = NativeAST.JSDocPrivateTag;
export type JSDocPropertyTag = NativeAST.JSDocPropertyTag;
export type JSDocProtectedTag = NativeAST.JSDocProtectedTag;
export type JSDocPublicTag = NativeAST.JSDocPublicTag;
export type JSDocReadonlyTag = NativeAST.JSDocReadonlyTag;
export type JSDocReturnTag = NativeAST.JSDocReturnTag;
export type JSDocSatisfiesTag = NativeAST.JSDocSatisfiesTag;
export type JSDocSeeTag = NativeAST.JSDocSeeTag;
export type JSDocSignature = NativeAST.JSDocSignature;
export type JSDocTemplateTag = NativeAST.JSDocTemplateTag;
export type JSDocText = NativeAST.JSDocText;
export type JSDocThisTag = NativeAST.JSDocThisTag;
export type JSDocThrowsTag = NativeAST.JSDocThrowsTag;
export type JSDocTypeExpression = NativeAST.JSDocTypeExpression;
export type JSDocTypeLiteral = NativeAST.JSDocTypeLiteral;
export type JSDocTypeTag = NativeAST.JSDocTypeTag;
export type JSDocTypedefTag = NativeAST.JSDocTypedefTag;
export type JSDocUnknownTag = NativeAST.JSDocUnknownTag;
export type JSDocVariadicType = NativeAST.JSDocVariadicType;
export type JsxAttribute = NativeAST.JsxAttribute;
export type JsxAttributeLike = NativeAST.JsxAttributeLike;
export type JsxAttributeList = NativeAST.JsxAttributeList;
export type JsxAttributeName = NativeAST.JsxAttributeName;
export type JsxAttributeValue = NativeAST.JsxAttributeValue;
export type JsxAttributes = NativeAST.JsxAttributes;
export type JsxChild = NativeAST.JsxChild;
export type JsxChildList = NativeAST.JsxChildList;
export type JsxClosingElement = NativeAST.JsxClosingElement;
export type JsxClosingFragment = NativeAST.JsxClosingFragment;
export type JsxElement = NativeAST.JsxElement;
export type JsxExpression = NativeAST.JsxExpression;
export type JsxFragment = NativeAST.JsxFragment;
export type JsxNamespacedName = NativeAST.JsxNamespacedName;
export type JsxOpeningElement = NativeAST.JsxOpeningElement;
export type JsxOpeningFragment = NativeAST.JsxOpeningFragment;
export type JsxOpeningLikeElement = NativeAST.JsxOpeningLikeElement;
export type JsxSelfClosingElement = NativeAST.JsxSelfClosingElement;
export type JsxSpreadAttribute = NativeAST.JsxSpreadAttribute;
export type JsxTagNameExpression = NativeAST.JsxTagNameExpression;
export type JsxTagNamePropertyAccess = NativeAST.JsxTagNamePropertyAccess;
export type JsxText = NativeAST.JsxText;
export type JsxTokenSyntaxKind = NativeAST.JsxTokenSyntaxKind;
export type KeywordExpressionSyntaxKind = NativeAST.KeywordExpressionSyntaxKind;
export type KeywordSyntaxKind = NativeAST.KeywordSyntaxKind;
export type KeywordTypeSyntaxKind = NativeAST.KeywordTypeSyntaxKind;
export type LabeledStatement = NativeAST.LabeledStatement;
export type LineAndCharacter = NativeAST.LineAndCharacter;
export type LiteralSyntaxKind = NativeAST.LiteralSyntaxKind;
export type LiteralToken = NativeAST.LiteralToken;
export type LiteralTypeNode = NativeAST.LiteralTypeNode;
export type LogicalOperator = NativeAST.LogicalOperator;
export type LogicalOperatorOrHigher = NativeAST.LogicalOperatorOrHigher;
export type LogicalOrCoalescingAssignmentOperator =
	NativeAST.LogicalOrCoalescingAssignmentOperator;
export type MappedDiagnosticDirective = NativeAST.MappedDiagnosticDirective;
export type MappedTypeNode = NativeAST.MappedTypeNode;
export type MemberName = NativeAST.MemberName;
export type MetaProperty = NativeAST.MetaProperty;
export type MethodDeclaration = NativeAST.MethodDeclaration;
export type MethodSignatureDeclaration = NativeAST.MethodSignatureDeclaration;
export type MinusToken = NativeAST.MinusToken;
export type MissingDeclaration = NativeAST.MissingDeclaration;
export type Modifier = NativeAST.Modifier;
export type ModifierLike = NativeAST.ModifierLike;
export type ModifierSyntaxKind = NativeAST.ModifierSyntaxKind;
export type ModuleBlock = NativeAST.ModuleBlock;
export type ModuleBody = NativeAST.ModuleBody;
export type ModuleDeclaration = NativeAST.ModuleDeclaration;
export type ModuleExportName = NativeAST.ModuleExportName;
export type ModuleName = NativeAST.ModuleName;
export type ModuleReference = NativeAST.ModuleReference;
export type MultiplicativeOperator = NativeAST.MultiplicativeOperator;
export type MultiplicativeOperatorOrHigher =
	NativeAST.MultiplicativeOperatorOrHigher;
export type NamedExportBindings = NativeAST.NamedExportBindings;
export type NamedExports = NativeAST.NamedExports;
export type NamedImportBindings = NativeAST.NamedImportBindings;
export type NamedImports = NativeAST.NamedImports;
export type NamedImportsOrExports = NativeAST.NamedImportsOrExports;
export type NamedTupleMember = NativeAST.NamedTupleMember;
export type NamespaceExport = NativeAST.NamespaceExport;
export type NamespaceExportDeclaration = NativeAST.NamespaceExportDeclaration;
export type NamespaceImport = NativeAST.NamespaceImport;
export type NewExpression = NativeAST.NewExpression;
export type NoSubstitutionTemplateLiteral =
	NativeAST.NoSubstitutionTemplateLiteral;
export type NodeBody = NativeAST.NodeBody;
export type NonNullExpression = NativeAST.NonNullExpression;
export type NotEmittedStatement = NativeAST.NotEmittedStatement;
export type NotEmittedTypeElement = NativeAST.NotEmittedTypeElement;
export type NullLiteral = NativeAST.NullLiteral;
export type NumericLiteral = NativeAST.NumericLiteral;
export type NumericOrStringLikeLiteral = NativeAST.NumericOrStringLikeLiteral;
export type ObjectAssignmentInitializer = NativeAST.ObjectAssignmentInitializer;
export type ObjectBindingPattern = NativeAST.ObjectBindingPattern;
export type ObjectDestructuringAssignment =
	NativeAST.ObjectDestructuringAssignment;
export type ObjectLiteralElementLike = NativeAST.ObjectLiteralElementLike;
export type ObjectLiteralExpression = NativeAST.ObjectLiteralExpression;
export type ObjectLiteralLikeNode = NativeAST.ObjectLiteralLikeNode;
export type ObjectTypeDeclaration = NativeAST.ObjectTypeDeclaration;
export type OmittedExpression = NativeAST.OmittedExpression;
export type OptionalTypeNode = NativeAST.OptionalTypeNode;
export type OutKeyword = NativeAST.OutKeyword;
export type OverrideKeyword = NativeAST.OverrideKeyword;
export type ParameterDeclaration = NativeAST.ParameterDeclaration;
export type ParameterList = NativeAST.ParameterList;
export type ParenthesizedExpression = NativeAST.ParenthesizedExpression;
export type ParenthesizedTypeNode = NativeAST.ParenthesizedTypeNode;
export type PartiallyEmittedExpression = NativeAST.PartiallyEmittedExpression;
export type Path = NativeAST.Path;
export type PlusToken = NativeAST.PlusToken;
export type PostfixUnaryExpression = NativeAST.PostfixUnaryExpression;
export type PostfixUnaryOperator = NativeAST.PostfixUnaryOperator;
export type PrefixUnaryExpression = NativeAST.PrefixUnaryExpression;
export type PrefixUnaryOperator = NativeAST.PrefixUnaryOperator;
export type PrivateIdentifier = NativeAST.PrivateIdentifier;
export type PrivateKeyword = NativeAST.PrivateKeyword;
export type PropertyAccessEntityNameExpression =
	NativeAST.PropertyAccessEntityNameExpression;
export type PropertyAccessExpression = NativeAST.PropertyAccessExpression;
export type PropertyAssignment = NativeAST.PropertyAssignment;
export type PropertyDeclaration = NativeAST.PropertyDeclaration;
export type PropertyDefinitionList = NativeAST.PropertyDefinitionList;
export type PropertyName = NativeAST.PropertyName;
export type PropertyNameLiteral = NativeAST.PropertyNameLiteral;
export type PropertySignatureDeclaration =
	NativeAST.PropertySignatureDeclaration;
export type ProtectedKeyword = NativeAST.ProtectedKeyword;
export type PseudoLiteralSyntaxKind = NativeAST.PseudoLiteralSyntaxKind;
export type PseudoLiteralToken = NativeAST.PseudoLiteralToken;
export type PublicKeyword = NativeAST.PublicKeyword;
export type PunctuationSyntaxKind = NativeAST.PunctuationSyntaxKind;
export type QualifiedName = NativeAST.QualifiedName;
export type QuestionDotToken = NativeAST.QuestionDotToken;
export type QuestionToken = NativeAST.QuestionToken;
export type ReadonlyKeyword = NativeAST.ReadonlyKeyword;
export type ReadonlyTextRange = NativeAST.ReadonlyTextRange;
export type RegularExpressionLiteral = NativeAST.RegularExpressionLiteral;
export type RelationalOperator = NativeAST.RelationalOperator;
export type RelationalOperatorOrHigher = NativeAST.RelationalOperatorOrHigher;
export type RestTypeNode = NativeAST.RestTypeNode;
export type ReturnStatement = NativeAST.ReturnStatement;
export type SatisfiesExpression = NativeAST.SatisfiesExpression;
export type SemicolonClassElement = NativeAST.SemicolonClassElement;
export type SetAccessorDeclaration = NativeAST.SetAccessorDeclaration;
export type ShiftOperator = NativeAST.ShiftOperator;
export type ShiftOperatorOrHigher = NativeAST.ShiftOperatorOrHigher;
export type ShorthandPropertyAssignment = NativeAST.ShorthandPropertyAssignment;
export type SignatureDeclaration = NativeAST.SignatureDeclaration;
export type SourceFile = NativeAST.SourceFile;
export type SpreadAssignment = NativeAST.SpreadAssignment;
export type SpreadElement = NativeAST.SpreadElement;
export type StatementList = NativeAST.StatementList;
export type StaticKeyword = NativeAST.StaticKeyword;
export type StringLiteral = NativeAST.StringLiteral;
export type StringLiteralLikeNode = NativeAST.StringLiteralLikeNode;
export type SuperExpression = NativeAST.SuperExpression;
export type SwitchStatement = NativeAST.SwitchStatement;
export type SyntaxList = NativeAST.SyntaxList;
export type SyntheticExpression = NativeAST.SyntheticExpression;
export type SyntheticReferenceExpression =
	NativeAST.SyntheticReferenceExpression;
export type TaggedTemplateExpression = NativeAST.TaggedTemplateExpression;
export type TemplateExpression = NativeAST.TemplateExpression;
export type TemplateHead = NativeAST.TemplateHead;
export type TemplateLiteral = NativeAST.TemplateLiteral;
export type TemplateLiteralToken = NativeAST.TemplateLiteralToken;
export type TemplateLiteralTypeNode = NativeAST.TemplateLiteralTypeNode;
export type TemplateLiteralTypeSpan = NativeAST.TemplateLiteralTypeSpan;
export type TemplateLiteralTypeSpanList = NativeAST.TemplateLiteralTypeSpanList;
export type TemplateMiddle = NativeAST.TemplateMiddle;
export type TemplateMiddleOrTail = NativeAST.TemplateMiddleOrTail;
export type TemplateSpan = NativeAST.TemplateSpan;
export type TemplateSpanList = NativeAST.TemplateSpanList;
export type TemplateTail = NativeAST.TemplateTail;
export type TextRange = NativeAST.TextRange;
export type ThisExpression = NativeAST.ThisExpression;
export type ThisTypeNode = NativeAST.ThisTypeNode;
export type ThrowStatement = NativeAST.ThrowStatement;
export type TokenSyntaxKind = NativeAST.TokenSyntaxKind;
export type TriviaSyntaxKind = NativeAST.TriviaSyntaxKind;
export type TrueLiteral = NativeAST.TrueLiteral;
export type TryStatement = NativeAST.TryStatement;
export type TupleTypeNode = NativeAST.TupleTypeNode;
export type TypeAliasDeclaration = NativeAST.TypeAliasDeclaration;
export type TypeArgumentList = NativeAST.TypeArgumentList;
export type TypeAssertion = NativeAST.TypeAssertion;
export type TypeElementList = NativeAST.TypeElementList;
export type TypeList = NativeAST.TypeList;
export type TypeLiteralNode = NativeAST.TypeLiteralNode;
export type TypeOfExpression = NativeAST.TypeOfExpression;
export type TypeOperatorNode = NativeAST.TypeOperatorNode;
export type TypeParameterDeclaration = NativeAST.TypeParameterDeclaration;
export type TypeParameterList = NativeAST.TypeParameterList;
export type TypePredicateNode = NativeAST.TypePredicateNode;
export type TypePredicateParameterName = NativeAST.TypePredicateParameterName;
export type TypeQueryNode = NativeAST.TypeQueryNode;
export type TypeReferenceNode = NativeAST.TypeReferenceNode;
export type UnionTypeNode = NativeAST.UnionTypeNode;
export type VariableDeclaration = NativeAST.VariableDeclaration;
export type VariableDeclarationList = NativeAST.VariableDeclarationList;
export type VariableDeclarationNodeList = NativeAST.VariableDeclarationNodeList;
export type VariableOrParameterDeclaration =
	NativeAST.VariableOrParameterDeclaration;
export type VariableOrPropertyDeclaration =
	NativeAST.VariableOrPropertyDeclaration;
export type VariableStatement = NativeAST.VariableStatement;
export type VoidExpression = NativeAST.VoidExpression;
export type WhileStatement = NativeAST.WhileStatement;
export type WithStatement = NativeAST.WithStatement;
export type YieldExpression = NativeAST.YieldExpression;
export type __String = NativeAST.__String;
export type Token<
	TKind extends NativeAST.TokenSyntaxKind = NativeAST.TokenSyntaxKind,
> = NativeAST.Token<TKind>;
export type AmpersandAmpersandEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.AmpersandAmpersandEqualsToken>;
export type AmpersandAmpersandToken =
	NativeAST.Token<NativeAST.SyntaxKind.AmpersandAmpersandToken>;
export type AmpersandEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.AmpersandEqualsToken>;
export type AmpersandToken =
	NativeAST.Token<NativeAST.SyntaxKind.AmpersandToken>;
export type AnyKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.AnyKeyword>;
export type AsKeyword = NativeAST.Token<NativeAST.SyntaxKind.AsKeyword>;
export type AsteriskAsteriskEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.AsteriskAsteriskEqualsToken>;
export type AsteriskAsteriskToken =
	NativeAST.Token<NativeAST.SyntaxKind.AsteriskAsteriskToken>;
export type AsteriskEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.AsteriskEqualsToken>;
export type AtToken = NativeAST.Token<NativeAST.SyntaxKind.AtToken>;
export type BacktickToken = NativeAST.Token<NativeAST.SyntaxKind.BacktickToken>;
export type BarBarEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.BarBarEqualsToken>;
export type BarBarToken = NativeAST.Token<NativeAST.SyntaxKind.BarBarToken>;
export type BarEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.BarEqualsToken>;
export type BarToken = NativeAST.Token<NativeAST.SyntaxKind.BarToken>;
export type BigIntKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BigIntKeyword>;
export type BooleanKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BooleanKeyword>;
export type BreakKeyword = NativeAST.Token<NativeAST.SyntaxKind.BreakKeyword>;
export type CaretEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.CaretEqualsToken>;
export type CaretToken = NativeAST.Token<NativeAST.SyntaxKind.CaretToken>;
export type CatchKeyword = NativeAST.Token<NativeAST.SyntaxKind.CatchKeyword>;
export type ClassKeyword = NativeAST.Token<NativeAST.SyntaxKind.ClassKeyword>;
export type CloseBraceToken =
	NativeAST.Token<NativeAST.SyntaxKind.CloseBraceToken>;
export type CloseBracketToken =
	NativeAST.Token<NativeAST.SyntaxKind.CloseBracketToken>;
export type CloseParenToken =
	NativeAST.Token<NativeAST.SyntaxKind.CloseParenToken>;
export type CommaToken = NativeAST.Token<NativeAST.SyntaxKind.CommaToken>;
export type ConflictMarkerTrivia =
	NativeAST.Token<NativeAST.SyntaxKind.ConflictMarkerTrivia>;
export type ConstructorKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.ConstructorKeyword>;
export type ContinueKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.ContinueKeyword>;
export type DebuggerKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.DebuggerKeyword>;
export type DeferKeyword = NativeAST.Token<NativeAST.SyntaxKind.DeferKeyword>;
export type DeleteKeyword = NativeAST.Token<NativeAST.SyntaxKind.DeleteKeyword>;
export type DoKeyword = NativeAST.Token<NativeAST.SyntaxKind.DoKeyword>;
export type ElseKeyword = NativeAST.Token<NativeAST.SyntaxKind.ElseKeyword>;
export type EnumKeyword = NativeAST.Token<NativeAST.SyntaxKind.EnumKeyword>;
export type EqualsEqualsEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.EqualsEqualsEqualsToken>;
export type EqualsEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.EqualsEqualsToken>;
export type ExclamationEqualsEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.ExclamationEqualsEqualsToken>;
export type ExclamationEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.ExclamationEqualsToken>;
export type ExtendsKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.ExtendsKeyword>;
export type FalseKeyword =
	NativeAST.KeywordExpression<NativeAST.SyntaxKind.FalseKeyword>;
export type FinallyKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.FinallyKeyword>;
export type ForKeyword = NativeAST.Token<NativeAST.SyntaxKind.ForKeyword>;
export type FromKeyword = NativeAST.Token<NativeAST.SyntaxKind.FromKeyword>;
export type FunctionKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.FunctionKeyword>;
export type GetKeyword = NativeAST.Token<NativeAST.SyntaxKind.GetKeyword>;
export type GlobalKeyword = NativeAST.Token<NativeAST.SyntaxKind.GlobalKeyword>;
export type GreaterThanEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.GreaterThanEqualsToken>;
export type GreaterThanGreaterThanEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanEqualsToken>;
export type GreaterThanGreaterThanGreaterThanEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken>;
export type GreaterThanGreaterThanGreaterThanToken =
	NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanGreaterThanToken>;
export type GreaterThanGreaterThanToken =
	NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanToken>;
export type GreaterThanToken =
	NativeAST.Token<NativeAST.SyntaxKind.GreaterThanToken>;
export type HashToken = NativeAST.Token<NativeAST.SyntaxKind.HashToken>;
export type IfKeyword = NativeAST.Token<NativeAST.SyntaxKind.IfKeyword>;
export type ImmediateKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.ImmediateKeyword>;
export type ImplementsKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.ImplementsKeyword>;
export type ImportKeyword =
	NativeAST.KeywordExpression<NativeAST.SyntaxKind.ImportKeyword>;
export type InferKeyword = NativeAST.Token<NativeAST.SyntaxKind.InferKeyword>;
export type InstanceOfKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.InstanceOfKeyword>;
export type InterfaceKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.InterfaceKeyword>;
export type IntrinsicKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.IntrinsicKeyword>;
export type IsKeyword = NativeAST.Token<NativeAST.SyntaxKind.IsKeyword>;
export type JSDocCommentTextToken =
	NativeAST.Token<NativeAST.SyntaxKind.JSDocCommentTextToken>;
export type JsxTextAllWhiteSpaces =
	NativeAST.Token<NativeAST.SyntaxKind.JsxTextAllWhiteSpaces>;
export type KeyOfKeyword = NativeAST.Token<NativeAST.SyntaxKind.KeyOfKeyword>;
export type LessThanEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.LessThanEqualsToken>;
export type LessThanLessThanEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.LessThanLessThanEqualsToken>;
export type LessThanLessThanToken =
	NativeAST.Token<NativeAST.SyntaxKind.LessThanLessThanToken>;
export type LessThanSlashToken =
	NativeAST.Token<NativeAST.SyntaxKind.LessThanSlashToken>;
export type LessThanToken = NativeAST.Token<NativeAST.SyntaxKind.LessThanToken>;
export type LetKeyword = NativeAST.Token<NativeAST.SyntaxKind.LetKeyword>;
export type MinusEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.MinusEqualsToken>;
export type MinusMinusToken =
	NativeAST.Token<NativeAST.SyntaxKind.MinusMinusToken>;
export type ModuleKeyword = NativeAST.Token<NativeAST.SyntaxKind.ModuleKeyword>;
export type MultiLineCommentTrivia =
	NativeAST.Token<NativeAST.SyntaxKind.MultiLineCommentTrivia>;
export type NamespaceKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.NamespaceKeyword>;
export type NeverKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NeverKeyword>;
export type NewKeyword = NativeAST.Token<NativeAST.SyntaxKind.NewKeyword>;
export type NewLineTrivia = NativeAST.Token<NativeAST.SyntaxKind.NewLineTrivia>;
export type NonTextFileMarkerTrivia =
	NativeAST.Token<NativeAST.SyntaxKind.NonTextFileMarkerTrivia>;
export type NullKeyword =
	NativeAST.KeywordExpression<NativeAST.SyntaxKind.NullKeyword>;
export type NumberKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NumberKeyword>;
export type ObjectKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.ObjectKeyword>;
export type OfKeyword = NativeAST.Token<NativeAST.SyntaxKind.OfKeyword>;
export type OpenBraceToken =
	NativeAST.Token<NativeAST.SyntaxKind.OpenBraceToken>;
export type OpenBracketToken =
	NativeAST.Token<NativeAST.SyntaxKind.OpenBracketToken>;
export type OpenParenToken =
	NativeAST.Token<NativeAST.SyntaxKind.OpenParenToken>;
export type PackageKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.PackageKeyword>;
export type PercentEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.PercentEqualsToken>;
export type PercentToken = NativeAST.Token<NativeAST.SyntaxKind.PercentToken>;
export type PlusEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.PlusEqualsToken>;
export type PlusPlusToken = NativeAST.Token<NativeAST.SyntaxKind.PlusPlusToken>;
export type QuestionQuestionEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.QuestionQuestionEqualsToken>;
export type QuestionQuestionToken =
	NativeAST.Token<NativeAST.SyntaxKind.QuestionQuestionToken>;
export type RequireKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.RequireKeyword>;
export type ReturnKeyword = NativeAST.Token<NativeAST.SyntaxKind.ReturnKeyword>;
export type SatisfiesKeyword =
	NativeAST.Token<NativeAST.SyntaxKind.SatisfiesKeyword>;
export type SemicolonToken =
	NativeAST.Token<NativeAST.SyntaxKind.SemicolonToken>;
export type SetKeyword = NativeAST.Token<NativeAST.SyntaxKind.SetKeyword>;
export type SingleLineCommentTrivia =
	NativeAST.Token<NativeAST.SyntaxKind.SingleLineCommentTrivia>;
export type SlashEqualsToken =
	NativeAST.Token<NativeAST.SyntaxKind.SlashEqualsToken>;
export type SlashToken = NativeAST.Token<NativeAST.SyntaxKind.SlashToken>;
export type StringKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.StringKeyword>;
export type SuperKeyword =
	NativeAST.KeywordExpression<NativeAST.SyntaxKind.SuperKeyword>;
export type SwitchKeyword = NativeAST.Token<NativeAST.SyntaxKind.SwitchKeyword>;
export type SymbolKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.SymbolKeyword>;
export type ThisKeyword =
	NativeAST.KeywordExpression<NativeAST.SyntaxKind.ThisKeyword>;
export type ThrowKeyword = NativeAST.Token<NativeAST.SyntaxKind.ThrowKeyword>;
export type TildeToken = NativeAST.Token<NativeAST.SyntaxKind.TildeToken>;
export type TrueKeyword =
	NativeAST.KeywordExpression<NativeAST.SyntaxKind.TrueKeyword>;
export type TryKeyword = NativeAST.Token<NativeAST.SyntaxKind.TryKeyword>;
export type TypeKeyword = NativeAST.Token<NativeAST.SyntaxKind.TypeKeyword>;
export type TypeOfKeyword = NativeAST.Token<NativeAST.SyntaxKind.TypeOfKeyword>;
export type UndefinedKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UndefinedKeyword>;
export type UniqueKeyword = NativeAST.Token<NativeAST.SyntaxKind.UniqueKeyword>;
export type Unknown = NativeAST.Token<NativeAST.SyntaxKind.Unknown>;
export type UnknownKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UnknownKeyword>;
export type UsingKeyword = NativeAST.Token<NativeAST.SyntaxKind.UsingKeyword>;
export type VarKeyword = NativeAST.Token<NativeAST.SyntaxKind.VarKeyword>;
export type VoidKeyword =
	NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.VoidKeyword>;
export type WhileKeyword = NativeAST.Token<NativeAST.SyntaxKind.WhileKeyword>;
export type WhitespaceTrivia =
	NativeAST.Token<NativeAST.SyntaxKind.WhitespaceTrivia>;
export type WithKeyword = NativeAST.Token<NativeAST.SyntaxKind.WithKeyword>;
export type YieldKeyword = NativeAST.Token<NativeAST.SyntaxKind.YieldKeyword>;
export type AnyNode = Node;

export type Body =
	| NativeAST.ArrowFunction
	| NativeAST.ConstructorDeclaration
	| NativeAST.FunctionDeclaration
	| NativeAST.FunctionExpression
	| NativeAST.GetAccessorDeclaration
	| NativeAST.MethodDeclaration
	| NativeAST.ModuleDeclaration
	| NativeAST.SetAccessorDeclaration;

export type ClassElement =
	| NativeAST.ClassStaticBlockDeclaration
	| NativeAST.ConstructorDeclaration
	| NativeAST.GetAccessorDeclaration
	| NativeAST.IndexSignatureDeclaration
	| NativeAST.MethodDeclaration
	| NativeAST.PropertyDeclaration
	| NativeAST.SemicolonClassElement
	| NativeAST.SetAccessorDeclaration;

export type ClassLike = NativeAST.ClassDeclaration | NativeAST.ClassExpression;

export type Declaration =
	| NativeAST.ArrowFunction
	| NativeAST.BinaryExpression
	| NativeAST.BindingElement
	| NativeAST.CallExpression
	| NativeAST.CallSignatureDeclaration
	| NativeAST.ClassDeclaration
	| NativeAST.ClassExpression
	| NativeAST.ClassStaticBlockDeclaration
	| NativeAST.ConstructSignatureDeclaration
	| NativeAST.ConstructorDeclaration
	| NativeAST.ConstructorTypeNode
	| NativeAST.EnumDeclaration
	| NativeAST.EnumMember
	| NativeAST.ExportAssignment
	| NativeAST.ExportDeclaration
	| NativeAST.ExportSpecifier
	| NativeAST.FunctionDeclaration
	| NativeAST.FunctionExpression
	| NativeAST.FunctionTypeNode
	| NativeAST.GetAccessorDeclaration
	| NativeAST.ImportClause
	| NativeAST.ImportDeclaration
	| NativeAST.ImportEqualsDeclaration
	| NativeAST.ImportSpecifier
	| NativeAST.IndexSignatureDeclaration
	| NativeAST.InterfaceDeclaration
	| NativeAST.JSDocSignature
	| NativeAST.JSDocTypeLiteral
	| NativeAST.JsxAttribute
	| NativeAST.JsxAttributes
	| NativeAST.MappedTypeNode
	| NativeAST.MethodDeclaration
	| NativeAST.MethodSignatureDeclaration
	| NativeAST.MissingDeclaration
	| NativeAST.ModuleDeclaration
	| NativeAST.NamedTupleMember
	| NativeAST.NamespaceExport
	| NativeAST.NamespaceExportDeclaration
	| NativeAST.NamespaceImport
	| NativeAST.NoSubstitutionTemplateLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.ParameterDeclaration
	| NativeAST.PropertyAssignment
	| NativeAST.PropertyDeclaration
	| NativeAST.PropertySignatureDeclaration
	| NativeAST.SemicolonClassElement
	| NativeAST.SetAccessorDeclaration
	| NativeAST.ShorthandPropertyAssignment
	| NativeAST.SpreadAssignment
	| NativeAST.TypeAliasDeclaration
	| NativeAST.TypeLiteralNode
	| NativeAST.TypeParameterDeclaration
	| NativeAST.VariableDeclaration;

export type Expression =
	| NativeAST.ArrayLiteralExpression
	| NativeAST.ArrowFunction
	| NativeAST.AsExpression
	| NativeAST.AwaitExpression
	| NativeAST.BigIntLiteral
	| NativeAST.BinaryExpression
	| NativeAST.CallExpression
	| NativeAST.ClassExpression
	| NativeAST.ConditionalExpression
	| NativeAST.DeleteExpression
	| NativeAST.ElementAccessExpression
	| NativeAST.ExpressionWithTypeArguments
	| NativeAST.FalseLiteral
	| NativeAST.FunctionExpression
	| NativeAST.Identifier
	| NativeAST.ImportExpression
	| NativeAST.JsxAttributes
	| NativeAST.JsxClosingFragment
	| NativeAST.JsxElement
	| NativeAST.JsxExpression
	| NativeAST.JsxFragment
	| NativeAST.JsxNamespacedName
	| NativeAST.JsxOpeningElement
	| NativeAST.JsxOpeningFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.JsxText
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.FalseKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.ImportKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.NullKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.SuperKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.ThisKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.TrueKeyword>
	| NativeAST.MetaProperty
	| NativeAST.NewExpression
	| NativeAST.NoSubstitutionTemplateLiteral
	| NativeAST.NonNullExpression
	| NativeAST.NullLiteral
	| NativeAST.NumericLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.OmittedExpression
	| NativeAST.ParenthesizedExpression
	| NativeAST.PartiallyEmittedExpression
	| NativeAST.PostfixUnaryExpression
	| NativeAST.PrefixUnaryExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.PropertyAccessExpression
	| NativeAST.RegularExpressionLiteral
	| NativeAST.SatisfiesExpression
	| NativeAST.SpreadElement
	| NativeAST.StringLiteral
	| NativeAST.SuperExpression
	| NativeAST.SyntheticExpression
	| NativeAST.SyntheticReferenceExpression
	| NativeAST.TaggedTemplateExpression
	| NativeAST.TemplateExpression
	| NativeAST.ThisExpression
	| NativeAST.TrueLiteral
	| NativeAST.TypeAssertion
	| NativeAST.TypeOfExpression
	| NativeAST.VoidExpression
	| NativeAST.YieldExpression;

export type FunctionLike =
	| NativeAST.ArrowFunction
	| NativeAST.CallSignatureDeclaration
	| NativeAST.ConstructSignatureDeclaration
	| NativeAST.ConstructorDeclaration
	| NativeAST.ConstructorTypeNode
	| NativeAST.FunctionDeclaration
	| NativeAST.FunctionExpression
	| NativeAST.FunctionTypeNode
	| NativeAST.GetAccessorDeclaration
	| NativeAST.IndexSignatureDeclaration
	| NativeAST.JSDocSignature
	| NativeAST.MethodDeclaration
	| NativeAST.MethodSignatureDeclaration
	| NativeAST.SetAccessorDeclaration;

export type FunctionLikeWithBody =
	| NativeAST.ArrowFunction
	| NativeAST.ConstructorDeclaration
	| NativeAST.FunctionDeclaration
	| NativeAST.FunctionExpression
	| NativeAST.GetAccessorDeclaration
	| NativeAST.MethodDeclaration
	| NativeAST.SetAccessorDeclaration;

export type IterationStatement =
	| NativeAST.DoStatement
	| NativeAST.ForInStatement
	| NativeAST.ForOfStatement
	| NativeAST.ForStatement
	| NativeAST.WhileStatement;

export type JSDocComment =
	| NativeAST.JSDocLink
	| NativeAST.JSDocLinkCode
	| NativeAST.JSDocLinkPlain
	| NativeAST.JSDocText;

export type JSDocTag =
	| NativeAST.JSDocAugmentsTag
	| NativeAST.JSDocCallbackTag
	| NativeAST.JSDocDeprecatedTag
	| NativeAST.JSDocImplementsTag
	| NativeAST.JSDocImportTag
	| NativeAST.JSDocOverloadTag
	| NativeAST.JSDocOverrideTag
	| NativeAST.JSDocParameterTag
	| NativeAST.JSDocPrivateTag
	| NativeAST.JSDocPropertyTag
	| NativeAST.JSDocProtectedTag
	| NativeAST.JSDocPublicTag
	| NativeAST.JSDocReadonlyTag
	| NativeAST.JSDocReturnTag
	| NativeAST.JSDocSatisfiesTag
	| NativeAST.JSDocSeeTag
	| NativeAST.JSDocTemplateTag
	| NativeAST.JSDocThisTag
	| NativeAST.JSDocThrowsTag
	| NativeAST.JSDocTypeTag
	| NativeAST.JSDocTypedefTag
	| NativeAST.JSDocUnknownTag;

export type JSDocType =
	| NativeAST.JSDocAllType
	| NativeAST.JSDocNonNullableType
	| NativeAST.JSDocNullableType
	| NativeAST.JSDocOptionalType
	| NativeAST.JSDocSignature
	| NativeAST.JSDocTypeLiteral
	| NativeAST.JSDocVariadicType;

export type KeywordExpression =
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.FalseKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.ImportKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.NullKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.SuperKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.ThisKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.TrueKeyword>;

export type KeywordTypeNode =
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.AnyKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BigIntKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BooleanKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.IntrinsicKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NeverKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NumberKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.ObjectKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.StringKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.SymbolKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UndefinedKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UnknownKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.VoidKeyword>;

export type LeftHandSideExpression =
	| NativeAST.ArrayLiteralExpression
	| NativeAST.BigIntLiteral
	| NativeAST.CallExpression
	| NativeAST.ClassExpression
	| NativeAST.ElementAccessExpression
	| NativeAST.ExpressionWithTypeArguments
	| NativeAST.FunctionExpression
	| NativeAST.Identifier
	| NativeAST.JsxAttributes
	| NativeAST.JsxElement
	| NativeAST.JsxFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.MetaProperty
	| NativeAST.NewExpression
	| NativeAST.NonNullExpression
	| NativeAST.NumericLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.ParenthesizedExpression
	| NativeAST.PartiallyEmittedExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.PropertyAccessExpression
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral
	| NativeAST.TaggedTemplateExpression
	| NativeAST.TemplateExpression;

export type LiteralExpression =
	| NativeAST.BigIntLiteral
	| NativeAST.NumericLiteral
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral;

export type LiteralLikeNode =
	| NativeAST.BigIntLiteral
	| NativeAST.JsxText
	| NativeAST.NoSubstitutionTemplateLiteral
	| NativeAST.NumericLiteral
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral
	| NativeAST.TemplateHead
	| NativeAST.TemplateMiddle
	| NativeAST.TemplateTail;

export type MemberExpression =
	| NativeAST.ArrayLiteralExpression
	| NativeAST.BigIntLiteral
	| NativeAST.ClassExpression
	| NativeAST.ElementAccessExpression
	| NativeAST.ExpressionWithTypeArguments
	| NativeAST.FunctionExpression
	| NativeAST.Identifier
	| NativeAST.JsxAttributes
	| NativeAST.JsxElement
	| NativeAST.JsxFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.MetaProperty
	| NativeAST.NewExpression
	| NativeAST.NumericLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.ParenthesizedExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.PropertyAccessExpression
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral
	| NativeAST.TaggedTemplateExpression
	| NativeAST.TemplateExpression;

export type Modifiers =
	| NativeAST.ArrowFunction
	| NativeAST.BinaryExpression
	| NativeAST.ClassDeclaration
	| NativeAST.ClassExpression
	| NativeAST.ClassStaticBlockDeclaration
	| NativeAST.ConstructorDeclaration
	| NativeAST.ConstructorTypeNode
	| NativeAST.EnumDeclaration
	| NativeAST.EnumMember
	| NativeAST.ExportAssignment
	| NativeAST.ExportDeclaration
	| NativeAST.FunctionDeclaration
	| NativeAST.FunctionExpression
	| NativeAST.FunctionTypeNode
	| NativeAST.GetAccessorDeclaration
	| NativeAST.ImportDeclaration
	| NativeAST.ImportEqualsDeclaration
	| NativeAST.IndexSignatureDeclaration
	| NativeAST.InterfaceDeclaration
	| NativeAST.MethodDeclaration
	| NativeAST.MethodSignatureDeclaration
	| NativeAST.MissingDeclaration
	| NativeAST.ModuleDeclaration
	| NativeAST.NamespaceExportDeclaration
	| NativeAST.ParameterDeclaration
	| NativeAST.PropertyAssignment
	| NativeAST.PropertyDeclaration
	| NativeAST.PropertySignatureDeclaration
	| NativeAST.SetAccessorDeclaration
	| NativeAST.ShorthandPropertyAssignment
	| NativeAST.TypeAliasDeclaration
	| NativeAST.TypeParameterDeclaration
	| NativeAST.VariableStatement;

export type NamedMember =
	| NativeAST.EnumMember
	| NativeAST.GetAccessorDeclaration
	| NativeAST.MethodDeclaration
	| NativeAST.MethodSignatureDeclaration
	| NativeAST.PropertyAssignment
	| NativeAST.PropertyDeclaration
	| NativeAST.PropertySignatureDeclaration
	| NativeAST.SetAccessorDeclaration
	| NativeAST.ShorthandPropertyAssignment;

export type Node =
	| NativeAST.AbstractKeyword
	| NativeAST.AccessorKeyword
	| NativeAST.ArrayBindingPattern
	| NativeAST.ArrayLiteralExpression
	| NativeAST.ArrayTypeNode
	| NativeAST.ArrowFunction
	| NativeAST.AsExpression
	| NativeAST.AssertKeyword
	| NativeAST.AssertsKeyword
	| NativeAST.AsteriskToken
	| NativeAST.AsyncKeyword
	| NativeAST.AwaitExpression
	| NativeAST.AwaitKeyword
	| NativeAST.BigIntLiteral
	| NativeAST.BinaryExpression
	| NativeAST.BindingElement
	| NativeAST.Block
	| NativeAST.BreakStatement
	| NativeAST.CallExpression
	| NativeAST.CallSignatureDeclaration
	| NativeAST.CaseBlock
	| NativeAST.CaseClause
	| NativeAST.CaseKeyword
	| NativeAST.CatchClause
	| NativeAST.ClassDeclaration
	| NativeAST.ClassExpression
	| NativeAST.ClassStaticBlockDeclaration
	| NativeAST.ColonToken
	| NativeAST.ComputedPropertyName
	| NativeAST.ConditionalExpression
	| NativeAST.ConditionalTypeNode
	| NativeAST.ConstKeyword
	| NativeAST.ConstructSignatureDeclaration
	| NativeAST.ConstructorDeclaration
	| NativeAST.ConstructorTypeNode
	| NativeAST.ContinueStatement
	| NativeAST.DebuggerStatement
	| NativeAST.DeclareKeyword
	| NativeAST.Decorator
	| NativeAST.DefaultClause
	| NativeAST.DefaultKeyword
	| NativeAST.DeleteExpression
	| NativeAST.DoStatement
	| NativeAST.DotDotDotToken
	| NativeAST.DotToken
	| NativeAST.ElementAccessExpression
	| NativeAST.EmptyStatement
	| NativeAST.EndOfFile
	| NativeAST.EnumDeclaration
	| NativeAST.EnumMember
	| NativeAST.EqualsGreaterThanToken
	| NativeAST.EqualsToken
	| NativeAST.ExclamationToken
	| NativeAST.ExportAssignment
	| NativeAST.ExportDeclaration
	| NativeAST.ExportKeyword
	| NativeAST.ExportSpecifier
	| NativeAST.ExpressionStatement
	| NativeAST.ExpressionWithTypeArguments
	| NativeAST.ExternalModuleReference
	| NativeAST.FalseLiteral
	| NativeAST.ForInStatement
	| NativeAST.ForOfStatement
	| NativeAST.ForStatement
	| NativeAST.FunctionDeclaration
	| NativeAST.FunctionExpression
	| NativeAST.FunctionTypeNode
	| NativeAST.GetAccessorDeclaration
	| NativeAST.HeritageClause
	| NativeAST.Identifier
	| NativeAST.IfStatement
	| NativeAST.ImportAttribute
	| NativeAST.ImportAttributes
	| NativeAST.ImportClause
	| NativeAST.ImportDeclaration
	| NativeAST.ImportEqualsDeclaration
	| NativeAST.ImportExpression
	| NativeAST.ImportSpecifier
	| NativeAST.ImportTypeNode
	| NativeAST.InKeyword
	| NativeAST.IndexSignatureDeclaration
	| NativeAST.IndexedAccessTypeNode
	| NativeAST.InferTypeNode
	| NativeAST.InterfaceDeclaration
	| NativeAST.IntersectionTypeNode
	| NativeAST.JSDoc
	| NativeAST.JSDocAllType
	| NativeAST.JSDocAugmentsTag
	| NativeAST.JSDocCallbackTag
	| NativeAST.JSDocDeprecatedTag
	| NativeAST.JSDocImplementsTag
	| NativeAST.JSDocImportTag
	| NativeAST.JSDocLink
	| NativeAST.JSDocLinkCode
	| NativeAST.JSDocLinkPlain
	| NativeAST.JSDocNameReference
	| NativeAST.JSDocNonNullableType
	| NativeAST.JSDocNullableType
	| NativeAST.JSDocOptionalType
	| NativeAST.JSDocOverloadTag
	| NativeAST.JSDocOverrideTag
	| NativeAST.JSDocParameterTag
	| NativeAST.JSDocPrivateTag
	| NativeAST.JSDocPropertyTag
	| NativeAST.JSDocProtectedTag
	| NativeAST.JSDocPublicTag
	| NativeAST.JSDocReadonlyTag
	| NativeAST.JSDocReturnTag
	| NativeAST.JSDocSatisfiesTag
	| NativeAST.JSDocSeeTag
	| NativeAST.JSDocSignature
	| NativeAST.JSDocTemplateTag
	| NativeAST.JSDocText
	| NativeAST.JSDocThisTag
	| NativeAST.JSDocThrowsTag
	| NativeAST.JSDocTypeExpression
	| NativeAST.JSDocTypeLiteral
	| NativeAST.JSDocTypeTag
	| NativeAST.JSDocTypedefTag
	| NativeAST.JSDocUnknownTag
	| NativeAST.JSDocVariadicType
	| NativeAST.JsxAttribute
	| NativeAST.JsxAttributes
	| NativeAST.JsxClosingElement
	| NativeAST.JsxClosingFragment
	| NativeAST.JsxElement
	| NativeAST.JsxExpression
	| NativeAST.JsxFragment
	| NativeAST.JsxNamespacedName
	| NativeAST.JsxOpeningElement
	| NativeAST.JsxOpeningFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.JsxSpreadAttribute
	| NativeAST.JsxText
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.FalseKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.ImportKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.NullKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.SuperKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.ThisKeyword>
	| NativeAST.KeywordExpression<NativeAST.SyntaxKind.TrueKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.AnyKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BigIntKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BooleanKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.IntrinsicKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NeverKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NumberKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.ObjectKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.StringKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.SymbolKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UndefinedKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UnknownKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.VoidKeyword>
	| NativeAST.LabeledStatement
	| NativeAST.LiteralTypeNode
	| NativeAST.MappedTypeNode
	| NativeAST.MetaProperty
	| NativeAST.MethodDeclaration
	| NativeAST.MethodSignatureDeclaration
	| NativeAST.MinusToken
	| NativeAST.MissingDeclaration
	| NativeAST.ModuleBlock
	| NativeAST.ModuleDeclaration
	| NativeAST.NamedExports
	| NativeAST.NamedImports
	| NativeAST.NamedTupleMember
	| NativeAST.NamespaceExport
	| NativeAST.NamespaceExportDeclaration
	| NativeAST.NamespaceImport
	| NativeAST.NewExpression
	| NativeAST.NoSubstitutionTemplateLiteral
	| NativeAST.NonNullExpression
	| NativeAST.NotEmittedStatement
	| NativeAST.NotEmittedTypeElement
	| NativeAST.NullLiteral
	| NativeAST.NumericLiteral
	| NativeAST.ObjectBindingPattern
	| NativeAST.ObjectLiteralExpression
	| NativeAST.OmittedExpression
	| NativeAST.OptionalTypeNode
	| NativeAST.OutKeyword
	| NativeAST.OverrideKeyword
	| NativeAST.ParameterDeclaration
	| NativeAST.ParenthesizedExpression
	| NativeAST.ParenthesizedTypeNode
	| NativeAST.PartiallyEmittedExpression
	| NativeAST.PlusToken
	| NativeAST.PostfixUnaryExpression
	| NativeAST.PrefixUnaryExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.PrivateKeyword
	| NativeAST.PropertyAccessExpression
	| NativeAST.PropertyAssignment
	| NativeAST.PropertyDeclaration
	| NativeAST.PropertySignatureDeclaration
	| NativeAST.ProtectedKeyword
	| NativeAST.PublicKeyword
	| NativeAST.QualifiedName
	| NativeAST.QuestionDotToken
	| NativeAST.QuestionToken
	| NativeAST.ReadonlyKeyword
	| NativeAST.RegularExpressionLiteral
	| NativeAST.RestTypeNode
	| NativeAST.ReturnStatement
	| NativeAST.SatisfiesExpression
	| NativeAST.SemicolonClassElement
	| NativeAST.SetAccessorDeclaration
	| NativeAST.ShorthandPropertyAssignment
	| NativeAST.SourceFile
	| NativeAST.SpreadAssignment
	| NativeAST.SpreadElement
	| NativeAST.StaticKeyword
	| NativeAST.StringLiteral
	| NativeAST.SuperExpression
	| NativeAST.SwitchStatement
	| NativeAST.SyntaxList
	| NativeAST.SyntheticExpression
	| NativeAST.SyntheticReferenceExpression
	| NativeAST.TaggedTemplateExpression
	| NativeAST.TemplateExpression
	| NativeAST.TemplateHead
	| NativeAST.TemplateLiteralTypeNode
	| NativeAST.TemplateLiteralTypeSpan
	| NativeAST.TemplateMiddle
	| NativeAST.TemplateSpan
	| NativeAST.TemplateTail
	| NativeAST.ThisExpression
	| NativeAST.ThisTypeNode
	| NativeAST.ThrowStatement
	| NativeAST.Token<NativeAST.SyntaxKind.AmpersandAmpersandEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AmpersandAmpersandToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AmpersandEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AmpersandToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AnyKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.AsKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.AsteriskAsteriskEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AsteriskAsteriskToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AsteriskEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.AtToken>
	| NativeAST.Token<NativeAST.SyntaxKind.BacktickToken>
	| NativeAST.Token<NativeAST.SyntaxKind.BarBarEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.BarBarToken>
	| NativeAST.Token<NativeAST.SyntaxKind.BarEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.BarToken>
	| NativeAST.Token<NativeAST.SyntaxKind.BigIntKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.BooleanKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.BreakKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.CaretEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.CaretToken>
	| NativeAST.Token<NativeAST.SyntaxKind.CatchKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ClassKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.CloseBraceToken>
	| NativeAST.Token<NativeAST.SyntaxKind.CloseBracketToken>
	| NativeAST.Token<NativeAST.SyntaxKind.CloseParenToken>
	| NativeAST.Token<NativeAST.SyntaxKind.CommaToken>
	| NativeAST.Token<NativeAST.SyntaxKind.ConflictMarkerTrivia>
	| NativeAST.Token<NativeAST.SyntaxKind.ConstructorKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ContinueKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.DebuggerKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.DeferKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.DeleteKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.DoKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ElseKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.EnumKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.EqualsEqualsEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.EqualsEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.ExclamationEqualsEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.ExclamationEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.ExtendsKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.FinallyKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ForKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.FromKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.FunctionKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.GetKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.GlobalKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.GreaterThanEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanGreaterThanToken>
	| NativeAST.Token<NativeAST.SyntaxKind.GreaterThanGreaterThanToken>
	| NativeAST.Token<NativeAST.SyntaxKind.GreaterThanToken>
	| NativeAST.Token<NativeAST.SyntaxKind.HashToken>
	| NativeAST.Token<NativeAST.SyntaxKind.IfKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ImmediateKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ImplementsKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.InferKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.InstanceOfKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.InterfaceKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.IntrinsicKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.IsKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.JSDocCommentTextToken>
	| NativeAST.Token<NativeAST.SyntaxKind.JsxTextAllWhiteSpaces>
	| NativeAST.Token<NativeAST.SyntaxKind.KeyOfKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.LessThanEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.LessThanLessThanEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.LessThanLessThanToken>
	| NativeAST.Token<NativeAST.SyntaxKind.LessThanSlashToken>
	| NativeAST.Token<NativeAST.SyntaxKind.LessThanToken>
	| NativeAST.Token<NativeAST.SyntaxKind.LetKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.MinusEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.MinusMinusToken>
	| NativeAST.Token<NativeAST.SyntaxKind.ModuleKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.MultiLineCommentTrivia>
	| NativeAST.Token<NativeAST.SyntaxKind.NamespaceKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.NeverKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.NewKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.NewLineTrivia>
	| NativeAST.Token<NativeAST.SyntaxKind.NonTextFileMarkerTrivia>
	| NativeAST.Token<NativeAST.SyntaxKind.NumberKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ObjectKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.OfKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.OpenBraceToken>
	| NativeAST.Token<NativeAST.SyntaxKind.OpenBracketToken>
	| NativeAST.Token<NativeAST.SyntaxKind.OpenParenToken>
	| NativeAST.Token<NativeAST.SyntaxKind.PackageKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.PercentEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.PercentToken>
	| NativeAST.Token<NativeAST.SyntaxKind.PlusEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.PlusPlusToken>
	| NativeAST.Token<NativeAST.SyntaxKind.QuestionQuestionEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.QuestionQuestionToken>
	| NativeAST.Token<NativeAST.SyntaxKind.RequireKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ReturnKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.SatisfiesKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.SemicolonToken>
	| NativeAST.Token<NativeAST.SyntaxKind.SetKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.SingleLineCommentTrivia>
	| NativeAST.Token<NativeAST.SyntaxKind.SlashEqualsToken>
	| NativeAST.Token<NativeAST.SyntaxKind.SlashToken>
	| NativeAST.Token<NativeAST.SyntaxKind.StringKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.SwitchKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.SymbolKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.ThrowKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.TildeToken>
	| NativeAST.Token<NativeAST.SyntaxKind.TryKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.TypeKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.TypeOfKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.UndefinedKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.UniqueKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.Unknown>
	| NativeAST.Token<NativeAST.SyntaxKind.UnknownKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.UsingKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.VarKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.VoidKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.WhileKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.WhitespaceTrivia>
	| NativeAST.Token<NativeAST.SyntaxKind.WithKeyword>
	| NativeAST.Token<NativeAST.SyntaxKind.YieldKeyword>
	| NativeAST.TrueLiteral
	| NativeAST.TryStatement
	| NativeAST.TupleTypeNode
	| NativeAST.TypeAliasDeclaration
	| NativeAST.TypeAssertion
	| NativeAST.TypeLiteralNode
	| NativeAST.TypeOfExpression
	| NativeAST.TypeOperatorNode
	| NativeAST.TypeParameterDeclaration
	| NativeAST.TypePredicateNode
	| NativeAST.TypeQueryNode
	| NativeAST.TypeReferenceNode
	| NativeAST.UnionTypeNode
	| NativeAST.VariableDeclaration
	| NativeAST.VariableDeclarationList
	| NativeAST.VariableStatement
	| NativeAST.VoidExpression
	| NativeAST.WhileStatement
	| NativeAST.WithStatement
	| NativeAST.YieldExpression;

export type NodeWithTypeArguments =
	| NativeAST.ImportTypeNode
	| NativeAST.TypeQueryNode
	| NativeAST.TypeReferenceNode;

export type ObjectLiteralElement =
	| NativeAST.GetAccessorDeclaration
	| NativeAST.JsxSpreadAttribute
	| NativeAST.MethodDeclaration
	| NativeAST.PropertyAssignment
	| NativeAST.SetAccessorDeclaration
	| NativeAST.ShorthandPropertyAssignment
	| NativeAST.SpreadAssignment;

export type PrimaryExpression =
	| NativeAST.ArrayLiteralExpression
	| NativeAST.BigIntLiteral
	| NativeAST.ClassExpression
	| NativeAST.FunctionExpression
	| NativeAST.Identifier
	| NativeAST.JsxAttributes
	| NativeAST.JsxElement
	| NativeAST.JsxFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.MetaProperty
	| NativeAST.NewExpression
	| NativeAST.NumericLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.ParenthesizedExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral
	| NativeAST.TemplateExpression;

export type Statement =
	| NativeAST.Block
	| NativeAST.BreakStatement
	| NativeAST.ClassDeclaration
	| NativeAST.ContinueStatement
	| NativeAST.DebuggerStatement
	| NativeAST.DoStatement
	| NativeAST.EmptyStatement
	| NativeAST.EnumDeclaration
	| NativeAST.ExportAssignment
	| NativeAST.ExportDeclaration
	| NativeAST.ExpressionStatement
	| NativeAST.ForInStatement
	| NativeAST.ForOfStatement
	| NativeAST.ForStatement
	| NativeAST.FunctionDeclaration
	| NativeAST.IfStatement
	| NativeAST.ImportDeclaration
	| NativeAST.ImportEqualsDeclaration
	| NativeAST.InterfaceDeclaration
	| NativeAST.LabeledStatement
	| NativeAST.MissingDeclaration
	| NativeAST.ModuleBlock
	| NativeAST.ModuleDeclaration
	| NativeAST.NamespaceExportDeclaration
	| NativeAST.NotEmittedStatement
	| NativeAST.ReturnStatement
	| NativeAST.SwitchStatement
	| NativeAST.ThrowStatement
	| NativeAST.TryStatement
	| NativeAST.TypeAliasDeclaration
	| NativeAST.VariableStatement
	| NativeAST.WhileStatement
	| NativeAST.WithStatement;

export type TemplateLiteralLikeNode =
	| NativeAST.NoSubstitutionTemplateLiteral
	| NativeAST.TemplateHead
	| NativeAST.TemplateMiddle
	| NativeAST.TemplateTail;

export type TypeElement =
	| NativeAST.CallSignatureDeclaration
	| NativeAST.ConstructSignatureDeclaration
	| NativeAST.GetAccessorDeclaration
	| NativeAST.IndexSignatureDeclaration
	| NativeAST.MethodSignatureDeclaration
	| NativeAST.NotEmittedTypeElement
	| NativeAST.PropertySignatureDeclaration
	| NativeAST.SetAccessorDeclaration;

export type TypeNode =
	| NativeAST.ArrayTypeNode
	| NativeAST.ConditionalTypeNode
	| NativeAST.ConstructorTypeNode
	| NativeAST.FunctionTypeNode
	| NativeAST.ImportTypeNode
	| NativeAST.IndexedAccessTypeNode
	| NativeAST.InferTypeNode
	| NativeAST.IntersectionTypeNode
	| NativeAST.JSDocAllType
	| NativeAST.JSDocNameReference
	| NativeAST.JSDocNonNullableType
	| NativeAST.JSDocNullableType
	| NativeAST.JSDocOptionalType
	| NativeAST.JSDocSignature
	| NativeAST.JSDocTypeExpression
	| NativeAST.JSDocTypeLiteral
	| NativeAST.JSDocVariadicType
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.AnyKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BigIntKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.BooleanKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.IntrinsicKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NeverKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.NumberKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.ObjectKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.StringKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.SymbolKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UndefinedKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.UnknownKeyword>
	| NativeAST.KeywordTypeNode<NativeAST.SyntaxKind.VoidKeyword>
	| NativeAST.LiteralTypeNode
	| NativeAST.MappedTypeNode
	| NativeAST.NamedTupleMember
	| NativeAST.OptionalTypeNode
	| NativeAST.ParenthesizedTypeNode
	| NativeAST.RestTypeNode
	| NativeAST.TemplateLiteralTypeNode
	| NativeAST.TemplateLiteralTypeSpan
	| NativeAST.ThisTypeNode
	| NativeAST.TupleTypeNode
	| NativeAST.TypeLiteralNode
	| NativeAST.TypeOperatorNode
	| NativeAST.TypePredicateNode
	| NativeAST.TypeQueryNode
	| NativeAST.TypeReferenceNode
	| NativeAST.UnionTypeNode;

export type UnaryExpression =
	| NativeAST.ArrayLiteralExpression
	| NativeAST.AwaitExpression
	| NativeAST.BigIntLiteral
	| NativeAST.CallExpression
	| NativeAST.ClassExpression
	| NativeAST.DeleteExpression
	| NativeAST.ElementAccessExpression
	| NativeAST.ExpressionWithTypeArguments
	| NativeAST.FunctionExpression
	| NativeAST.Identifier
	| NativeAST.JsxAttributes
	| NativeAST.JsxElement
	| NativeAST.JsxFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.MetaProperty
	| NativeAST.NewExpression
	| NativeAST.NonNullExpression
	| NativeAST.NumericLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.ParenthesizedExpression
	| NativeAST.PartiallyEmittedExpression
	| NativeAST.PostfixUnaryExpression
	| NativeAST.PrefixUnaryExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.PropertyAccessExpression
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral
	| NativeAST.TaggedTemplateExpression
	| NativeAST.TemplateExpression
	| NativeAST.TypeAssertion
	| NativeAST.TypeOfExpression
	| NativeAST.VoidExpression;

export type UnionOrIntersectionTypeNode =
	| NativeAST.IntersectionTypeNode
	| NativeAST.UnionTypeNode;

export type UpdateExpression =
	| NativeAST.ArrayLiteralExpression
	| NativeAST.BigIntLiteral
	| NativeAST.CallExpression
	| NativeAST.ClassExpression
	| NativeAST.ElementAccessExpression
	| NativeAST.ExpressionWithTypeArguments
	| NativeAST.FunctionExpression
	| NativeAST.Identifier
	| NativeAST.JsxAttributes
	| NativeAST.JsxElement
	| NativeAST.JsxFragment
	| NativeAST.JsxSelfClosingElement
	| NativeAST.MetaProperty
	| NativeAST.NewExpression
	| NativeAST.NonNullExpression
	| NativeAST.NumericLiteral
	| NativeAST.ObjectLiteralExpression
	| NativeAST.ParenthesizedExpression
	| NativeAST.PartiallyEmittedExpression
	| NativeAST.PostfixUnaryExpression
	| NativeAST.PrefixUnaryExpression
	| NativeAST.PrivateIdentifier
	| NativeAST.PropertyAccessExpression
	| NativeAST.RegularExpressionLiteral
	| NativeAST.StringLiteral
	| NativeAST.TaggedTemplateExpression
	| NativeAST.TemplateExpression;

export type LeftHandSideExpressionParent = Expression | NativeAST.Decorator;
