/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/svelte`
 */
// #region Variables
export declare const svelte: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Reports raw special Svelte elements that should use the `svelte:` prefix.";
  readonly id: "rawSpecialElements";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "rawSpecialElement", undefined>]>;
// #endregion