/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/yaml`
 */
// #region Variables
export declare const yaml: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, "all", [import("@flint.fyi/core").Rule<{
  readonly description: "Prefer block-style mappings over flow-style mappings.";
  readonly id: "blockMappings";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferBlock", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer block style sequences over flow style sequences.";
  readonly id: "blockSequences";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "flowSequence", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports empty YAML documents that contain only document markers.";
  readonly id: "emptyDocuments";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyDocument", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports empty mapping keys.";
  readonly id: "emptyMappingKeys";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyKey", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports empty mapping values.";
  readonly id: "emptyMappingValues";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyValue", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports empty sequence entries.";
  readonly id: "emptySequenceEntries";
  readonly presets: readonly ["logical"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "emptyEntry", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Enforces consistent YAML file extensions.";
  readonly id: "fileExtensions";
  readonly presets: readonly ["stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "wrongExtension", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Reports trailing zeros in numeric values.";
  readonly id: "numericTrailingZeros";
  readonly presets: readonly ["stylistic", "stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "trailingZeros", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Prefer plain style scalars over quoted scalars.";
  readonly id: "plainScalars";
  readonly presets: readonly ["stylisticStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "preferPlain", undefined>, import("@flint.fyi/core").Rule<{
  readonly description: "Enforces mapping keys to be strings.";
  readonly id: "stringMappingKeys";
  readonly presets: readonly ["logical", "logicalStrict"];
} & {
  readonly pluginId: string;
  readonly url: string;
}, "nonStringKey", undefined>]>;
// #endregion