/**
 * Generated by tsnapi — public API snapshot of `@flint.fyi/nuxt`
 */
// #region Variables
export declare const nuxt: import("@flint.fyi/core").Plugin<import("@flint.fyi/core").RuleAbout<string>, string | undefined, []>;
// #endregion