name: OctoGuide

on: # zizmor: ignore[dangerous-triggers] This workflow does not check out or execute pull request code.
  discussion:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - deleted
      - edited
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request_review_comment:
    types:
      - created
      - deleted
      - edited
  pull_request_target:
    types:
      - edited
      - opened

permissions:
  discussions: write
  issues: write
  pull-requests: write

jobs:
  octoguide:
    runs-on: ubuntu-slim
    steps:
      - uses: OctoGuide/bot@7fb7583381525bcdd9aabbfab291e21bae8de81e # 0.26.0
        with:
          config: strict
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-associations: "FIRST_TIMER,FIRST_TIME_CONTRIBUTOR,CONTRIBUTOR"
          rules: |
            {
              "pr-body-descriptive": {
                "include-associations": [
                  "COLLABORATOR",
                  "CONTRIBUTOR",
                  "FIRST_TIME_CONTRIBUTOR",
                  "FIRST_TIMER",
                  "MEMBER",
                  "OWNER"
                ]
              },
              "pr-title-conventional": {
                "include-associations": [
                  "COLLABORATOR",
                  "CONTRIBUTOR",
                  "FIRST_TIME_CONTRIBUTOR",
                  "FIRST_TIMER",
                  "MEMBER",
                  "OWNER"
                ]
              }
            }
