name: OctoGuide

on: # zizmor: ignore[dangerous-triggers] This workflow does not check out or execute pull request code.
  discussion:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - deleted
      - edited
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request_review_comment:
    types:
      - created
      - deleted
      - edited
  pull_request_target:
    types:
      - edited
      - opened

permissions:
  discussions: write
  issues: write
  pull-requests: write

jobs:
  octoguide:
    runs-on: ubuntu-slim
    steps:
      - uses: OctoGuide/bot@990f9bb3d914189128a7fd7d01490a2d9037e1f1 # 0.23.2
        with:
          config: strict
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-associations: "FIRST_TIMER,FIRST_TIME_CONTRIBUTOR,CONTRIBUTOR"
