name: Package Previews

on:
  pull_request: ~
  push:
    branches:
      - main

permissions: {}

jobs:
  publish:
    if: github.event.repository.fork != true
    name: Publish Package Previews
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
        with:
          cache: false
      - run: pnpm build
      - run: pnpm exec pkg-pr-new publish --pnpm --packageManager=pnpm --commentWithDev --commentWithSha --comment=off --json "$RUNNER_TEMP/package-previews.json" './packages/*'
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: github.event_name == 'pull_request'
        with:
          name: package-previews
          path: ${{ runner.temp }}/package-previews.json
          if-no-files-found: error
