name: PR Review Requested

on: # zizmor: ignore[dangerous-triggers] This workflow does not check out or execute pull request code.
  pull_request_target:
    types:
      - review_requested

permissions:
  pull-requests: write

jobs:
  pr_review_requested:
    runs-on: ubuntu-slim
    steps:
      - name: Remove waiting for author label
        run: >-
          gh issue edit "${PULL_REQUEST_NUMBER}" --remove-label "status: waiting for author"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      - if: failure()
        run: |
          echo "Don't worry if the previous step failed."
          echo "The label may already be absent."
