name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.event.repository.fork != true
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: $/.github/actions/setup
        with:
          cache: false

      - name: Create Token
        id: create_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.FLINT_TOKENS_BOT_CLIENT_ID }}
          permission-contents: write
          permission-pull-requests: write
          private-key: ${{ secrets.FLINT_TOKENS_BOT_PRIVATE_KEY }}

      - name: Changesets Release
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          github-token: ${{ steps.create_token.outputs.token }}
          publish-script: pnpm release
